// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a material renders, in V-Ray's terms (a material's Appearance tab).
 */
export type Appearance = { 
/**
 * The library preset it was made from.
 */
preset: string | null, 
/**
 * Reflection glossiness's complement: 0 mirror-sharp, 1 fully matte.
 */
roughness: number, 
/**
 * 0 dielectric (paint, wood, stone), 1 metal.
 */
metalness: number, 
/**
 * Reflection amount (specular), 0–1.
 */
reflection: number, 
/**
 * Refraction (transparency), 0–1: glass is 1.
 */
refraction: number, 
/**
 * Index of refraction.
 */
ior: number, 
/**
 * Bump (normal map) strength, 0–2.
 */
bump: number, 
/**
 * A texture: a Poly Haven set id, or `proc:` and a procedural pattern.
 */
texture: string | null, 
/**
 * Real-world size of one texture tile (mm), as V-Ray's real-world mapping.
 */
scale: number, 
/**
 * Multiplies a photo texture's colour (white keeps it as photographed).
 */
tint: [number, number, number], 
/**
 * Use the texture's colour; off keeps only its relief and gloss, painted in the
 * material's colour (painted brick, coloured plaster).
 */
textureColor: boolean, 
/**
 * Clear coat (lacquer, varnish, polish), 0–1.
 */
coat: number, 
/**
 * Fabric sheen, 0–1.
 */
sheen: number, };
