// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { NamedItem } from "./NamedItem";
import type { ParamDef } from "./ParamDef";
import type { ProjectStatus } from "./ProjectStatus";
import type { RufplanLink } from "./RufplanLink";
import type { StageItem } from "./StageItem";
import type { ViewInfo } from "./ViewInfo";

/**
 * Everything the UI shows outside the drawing canvases. Returned after every change.
 */
export type AppState = { project: ProjectStatus, 
/**
 * Bumps on every model change; canvases refetch when it changes.
 */
revision: number, views: Array<ViewInfo>, levels: Array<NamedItem>, wallTypes: Array<NamedItem>, floorTypes: Array<NamedItem>, ceilingTypes: Array<NamedItem>, doorTypes: Array<NamedItem>, windowTypes: Array<NamedItem>, roofTypes: Array<NamedItem>, stages: Array<StageItem>, currentStage: ElementId | null, projectInfo: ElementId | null, projectName: string, undo: string | null, redo: string | null, 
/**
 * Issued sets, oldest first.
 */
issuances: Array<NamedItem>, 
/**
 * The Rufplan.io project this model publishes to.
 */
rufplan: RufplanLink | null, 
/**
 * User-defined project parameters.
 */
paramDefs: Array<ParamDef>, };
