// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";
import type { ElementId } from "./ElementId";

/**
 * A type or material for the Keynote Manager's Assignments tab.
 */
export type Assignable = { id: ElementId, category: Category, name: string, key?: string, };
