// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The bark's texture.
 */
export type Bark = "Smooth" | "Furrowed" | "Plated" | "Papery" | "Mottled" | "Fibrous" | "Palm" | "Green";
