// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MaterialSpec } from "./MaterialSpec";
import type { RoofKind } from "./RoofKind";
import type { StorySpec } from "./StorySpec";
import type { Structure } from "./Structure";

/**
 * A building as Claude plans it.
 */
export type BuildingSpec = { name: string, 
/**
 * A few sentences on the design, for the owner.
 */
summary: string, stories: Array<StorySpec>, roof: RoofKind, 
/**
 * Roof pitch, rise per 12 (hip and gable).
 */
pitch: number, structure: Structure, materials: MaterialSpec, };
