// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What was built.
 */
export type BuildReport = { name: string, levels: number, walls: number, doors: number, windows: number, floors: number, rooms: number, stairs: number, roofs: number, materials: number, warnings: Array<string>, };
