// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MaterialSpec } from "./MaterialSpec";
import type { PlantingSpec } from "./PlantingSpec";
import type { RoofKind } from "./RoofKind";
import type { StorySpec } from "./StorySpec";
import type { Structure } from "./Structure";
import type { WindowChoice } from "./WindowChoice";

/**
 * A building as Claude plans it.
 */
export type BuildingSpec = { name: string, 
/**
 * A few sentences on the design, for the owner.
 */
summary: string, stories: Array<StorySpec>, roof: RoofKind, 
/**
 * Roof pitch, rise per 12 (hip and gable).
 */
pitch: number, structure: Structure, materials: MaterialSpec, windows: WindowChoice, 
/**
 * The architect or work it's designed after, if any (ADR-099).
 */
precedent: string, 
/**
 * A fascia profile (studio-core `fascia`) on every roof edge.
 */
fascia?: string, 
/**
 * Roof overhang, feet (1.5 when absent).
 */
overhang?: number, 
/**
 * Columns under the outer corners of cantilevered upper floors.
 */
cantileverColumns: boolean, 
/**
 * Lawn, trees, foundation beds and walks round the building.
 */
landscape: boolean, 
/**
 * Furniture in the rooms and on the terraces.
 */
furnish: boolean, planting: PlantingSpec, };
