// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What was built.
 */
export type BuildReport = { name: string, levels: number, walls: number, doors: number, windows: number, floors: number, rooms: number, stairs: number, roofs: number, materials: number, 
/**
 * Porches, terraces, decks and courtyards (ADR-099).
 */
outdoor: number, columns: number, railings: number, plants: number, furniture: number, 
/**
 * Dimensions on the plans.
 */
dimensions: number, 
/**
 * Sheets laid out for its CD set (by the app, ADR-099).
 */
sheets: number, warnings: Array<string>, };
