// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The building types sets are tailored to.
 */
export type BuildingType = "SingleFamily" | "Duplex" | "Townhouses" | "GardenApartments" | "MidRiseApartments" | "MixedUse" | "Hotel";
