// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Building types a library fixture is typical of (the picker's filter).
 */
export type BuildingUse = "Residential" | "Office" | "Retail" | "Hospitality" | "Healthcare" | "Education" | "Industrial" | "Exterior";
