// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingType } from "./BuildingType";

/**
 * A building type as the dialog lists it.
 */
export type BuildingTypeOption = { id: BuildingType, label: string, };
