// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A camera in model space (mm, z up), for the 3D view and the renderer.
 */
export type CameraPose = { eye: [number, number, number], target: [number, number, number], fov: number, };
