// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";
import type { ElementId } from "./ElementId";

/**
 * One element's cut on one face of the section box.
 */
export type Cap = { el: ElementId, category: Category, 
/**
 * The element's shaded colour, when it has one (else by category, as its mesh).
 */
color: [number, number, number] | null, exterior: boolean, 
/**
 * The cut, filled: triangles, 9 floats each (mm, z-up), on the box face.
 */
positions: Array<number>, 
/**
 * The cut's outline, 6 floats a segment.
 */
outline: Array<number>, 
/**
 * Lines inside the cut (a wall's layer boundaries), 6 floats a segment.
 */
inner: Array<number>, };
