// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Element category, used for indexing, browser grouping and visibility.
 */
export type Category = "Level" | "Grid" | "WallType" | "Wall" | "FloorType" | "Floor" | "CeilingType" | "Ceiling" | "View" | "ProjectInfo" | "Stage" | "DoorType" | "Door" | "WindowType" | "Window" | "Room" | "Dimension" | "TextNote" | "Sheet" | "Viewport";
