// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Element category, used for indexing, browser grouping and visibility.
 */
export type Category = "Level" | "Grid" | "WallType" | "Wall" | "FloorType" | "Floor" | "CeilingType" | "Ceiling" | "View" | "ProjectInfo" | "Stage" | "DoorType" | "Door" | "WindowType" | "Window" | "Room" | "Dimension" | "TextNote" | "Sheet" | "Viewport" | "Tag" | "Issuance" | "RoofType" | "Roof" | "Stair" | "ColumnType" | "Column" | "BeamType" | "Beam" | "RailingType" | "Railing" | "Material" | "RoomSeparator" | "ElevationMarker" | "ElevationMarkerType" | "Site" | "Standards" | "SpecBook" | "GroupType" | "FfeType" | "RenderImage" | "Group" | "SpotElevation" | "NorthArrow" | "GraphicScale" | "KeyPlan" | "SpotSlope" | "DetailLine" | "ModelLine" | "LightingFixtureType" | "LightingFixture" | "WallOpening" | "PlantingType" | "Planting" | "GroundRegion" | "GrassPatch" | "GenericModel" | "Furniture" | "Casework" | "SpecialtyEquipment" | "PlumbingFixture" | "FilledRegion" | "DetailComponent" | "ViewReference" | "Workset" | "StructuralScheme" | "KeynoteTable" | "KeynoteTag" | "MepScheme";
