// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";

/**
 * A choice in the Family Category and Parameters dialog.
 */
export type CategoryChoice = { category: Category, label: string, };
