// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a species grows well, for the library's filter.
 */
export type Climate = "Cold" | "Temperate" | "Mediterranean" | "Tropical" | "Arid";
