// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CloudStatus = { 
/**
 * False when this build has no Rufplan anon key.
 */
configured: boolean, signedIn: boolean, email: string | null, name: string | null, };
