// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A column's cross-section (mm).
 */
export type ColumnShape = { "Rectangular": { width: number, depth: number, } } | { "Round": { diameter: number, } } | { "WideFlange": { depth: number, flange: number, flange_t: number, web_t: number, } };
