// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Family } from "./Family";

/**
 * A component type for the UI's type selector.
 */
export type ComponentTypeInfo = { key: string, family: Family, familyLabel: string, name: string, lineBased: boolean, };
