// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compass direction an elevation view looks toward.
 */
export type Compass = "North" | "South" | "East" | "West";
