// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContourLabel = { 
/**
 * On the contour (project mm, z-up), at the middle of its longest run.
 */
at: [number, number, number], text: string, major: boolean, };
