// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Versions of the running app and its core crates.
 */
export type CoreVersion = { app: string, core: string, io: string, 
/**
 * Project file schema version this build writes.
 */
schemaVersion: number, };
