// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreKind } from "./CoreKind";
import type { ElementId } from "./ElementId";
import type { Pt } from "./Pt";

export type CoreFeature = { kind: CoreKind, level: ElementId, min: Pt, max: Pt, };
