// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How one scheme scored on one criterion (0–1).
 */
export type Criterion = { name: string, score: number, note: string, };
