// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pt } from "./Pt";

/**
 * A view's crop region in view coordinates (mm).
 */
export type CropBox = { min: Pt, max: Pt, };
