// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The crown's shape (the envelope the branches fill).
 */
export type CrownForm = "Round" | "Oval" | "Vase" | "Columnar" | "Pyramidal" | "Conical" | "Weeping" | "Spreading" | "Umbrella" | "Irregular" | "PalmHead" | "Mound" | "Upright" | "Fountain" | "Rosette" | "Box" | "Cactus";
