// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a material's cut face is hatched in plans and sections.
 */
export type CutPattern = "None" | "Insulation" | "Rigid" | "Masonry" | "Concrete" | "Wood" | "Solid";
