// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A view's Detail Level (ADR-067), as in Revit: how much of each element it draws.
 * Coarse: walls in solid poché, doors and windows as bare openings. Medium: wall core
 * boundaries and frames. Fine: every layer with its cut pattern, casings and muntins.
 */
export type DetailLevel = "Coarse" | "Medium" | "Fine";
