// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A detail in the library.
 */
export type DetailInfo = { id: string, name: string, category: string, 
/**
 * Drawing scale denominator: the scale this kind of detail is usually drawn at.
 */
scale: number, scaleLabel: string, description: string, 
/**
 * One you saved (ADR-073), which you can delete.
 */
user: boolean, };
