// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";

/**
 * Where a dimension end is attached, so it follows the model. Lengths in mm.
 */
export type DimAnchor = { "Wall": { wall: ElementId, t: number, side: number, } } | { "Grid": { grid: ElementId, t: number, } };
