// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a dimension measures (ADR-040): Revit's Aligned (across the references it was
 * picked from) or Linear (horizontal or vertical).
 */
export type DimKind = "Aligned" | "Linear";
