// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DimAnchor } from "./DimAnchor";
import type { Pt } from "./Pt";

/**
 * A reference of a dimension string between its first and last (ADR-040).
 */
export type DimRef = { at: Pt, anchor: DimAnchor | null, };
