// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscontinuityKind } from "./DiscontinuityKind";
import type { ElementId } from "./ElementId";
import type { Pt } from "./Pt";

export type Discontinuity = { kind: DiscontinuityKind, level: ElementId, at: Pt, message: string, };
