// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Item } from "./Item";
import type { ViewType } from "./ViewType";

export type DisplayList = { viewType: ViewType, 
/**
 * Drawing scale denominator.
 */
scale: number, 
/**
 * [min x, min y, max x, max y] in model mm.
 */
bounds: [number, number, number, number], items: Array<Item>, };
