// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DoorSpec } from "./DoorSpec";

export type DoorPresetInfo = { spec: DoorSpec, name: string, };
