// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Built-in door families (ADR-033, see `doors`). `SingleFlush` and `DoubleFlush` are the
 * single and double swing families (their leaf style is a type option); the names stay
 * for files saved before door families.
 */
export type DoorFamily = "SingleFlush" | "DoubleFlush" | "Sidelites" | "SlidingGlass" | "Pocket" | "Barn" | "Bifold" | "FoldingWall" | "Storefront" | "Garage";
