// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DoorFamily } from "./DoorFamily";
import type { DoorFinish } from "./DoorFinish";
import type { LeafStyle } from "./LeafStyle";

/**
 * A door type to load. Lengths mm.
 */
export type DoorSpec = { family: DoorFamily, leaf: LeafStyle, panels: number, width: number, height: number, finish: DoorFinish | null, };
