// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Leaf and frame finish (its colour in 3D and renderings).
 */
export type DoorFinish = "PaintedWhite" | "PaintedBlack" | "PaintedGray" | "StainedOak" | "Walnut" | "Aluminum" | "Bronze";
