// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Built-in door families (code-defined for v0.1, see DATA_MODEL.md).
 */
export type DoorFamily = "SingleFlush" | "DoubleFlush";
