// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DoorFamily } from "./DoorFamily";
import type { DoorFinish } from "./DoorFinish";
import type { LeafOption } from "./LeafOption";

export type DoorFamilyInfo = { family: DoorFamily, label: string, description: string, 
/**
 * Leaf styles it comes in, as (id, label); empty for glass and garage doors.
 */
leaves: Array<LeafOption>, 
/**
 * (min, max) of its panel count, when it has one.
 */
panels: [number, number] | null, panelsLabel: string, defaultFinish: DoorFinish, };
