// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DoorFinish } from "./DoorFinish";

export type DoorFinishOption = { id: DoorFinish, label: string, color: [number, number, number], };
