// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DoorFamilyInfo } from "./DoorFamilyInfo";
import type { DoorFinishOption } from "./DoorFinishOption";
import type { DoorPresetInfo } from "./DoorPresetInfo";

export type DoorLibrary = { families: Array<DoorFamilyInfo>, presets: Array<DoorPresetInfo>, finishes: Array<DoorFinishOption>, };
