// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WindowPreview } from "./WindowPreview";

export type DoorSpecPreview = { name: string, preview: WindowPreview, };
