// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { Pt } from "./Pt";

/**
 * An area that drags as a whole (a view title on a sheet, ADR-039): pressing inside it
 * and dragging calls `drag_handle(id, key, at + the drag)`.
 */
export type DragArea = { id: ElementId, key: string, min: Pt, max: Pt, 
/**
 * The point the drag moves (sent moved by the drag).
 */
at: Pt, };
