// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Options-bar settings of the draw tools (lengths in mm).
 */
export type DrawOptions = { offset: number, 
/**
 * Fillet radius for chained lines and rectangles (None: sharp corners).
 */
radius: number | null, sides: number, };
