// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Revit's boundary line draw tools.
 */
export type DrawTool = "Line" | "Rectangle" | "InscribedPolygon" | "CircumscribedPolygon" | "Circle" | "StartEndRadiusArc" | "CenterEndsArc";
