// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditPreview } from "./EditPreview";
import type { ModelEdit } from "./ModelEdit";

/**
 * Claude's proposal and what it would change (or why it can't be done).
 */
export type EditPlan = { edit: ModelEdit, preview: EditPreview | null, error: string | null, };
