// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";

/**
 * What an edit changes, for the preview card.
 */
export type EditPreview = { category: string, parameter: string, from: string, to: string, scope: string, count: number, 
/**
 * The elements it changes, to highlight.
 */
ids: Array<ElementId>, summary: string, 
/**
 * For a plan of several operations (ADR-051): one line per step, and what it creates,
 * changes and deletes by category ("4 Walls").
 */
steps: Array<string>, created: Array<string>, changed: Array<string>, deleted: Array<string>, };
