// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";

/**
 * What an edit changes, for the preview card.
 */
export type EditPreview = { category: string, parameter: string, from: string, to: string, scope: string, count: number, 
/**
 * The elements it changes, to highlight.
 */
ids: Array<ElementId>, summary: string, };
