// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable element identity (UUID v7). Serialized as a hyphenated string.
 */
export type ElementId = string;
