// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Family = "BreakLine" | "Plywood" | "Gypsum" | "CutLumber" | "LumberSide" | "Header" | "BattInsulation" | "RigidInsulation" | "BrickCoursing" | "CmuCoursing" | "Flashing" | "AnchorBolt" | "Sealant" | "Rebar" | "WideFlange" | "MetalStud" | "SteelAngle";
