// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FasciaPart } from "./FasciaPart";

export type FasciaSpec = { name: string, 
/**
 * What it is and where it's typical.
 */
description: string, parts: Array<FasciaPart>, 
/**
 * Finish color (sRGB).
 */
color: [number, number, number], 
/**
 * A material library preset for the finish ("metal-matte-black"…), or empty.
 */
finish: string, };
