// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One rectangle of a fascia profile (mm): from `out0` to `out1` outward of the roof edge,
 * and from `z0` to `z1` relative to the roof's top surface there.
 */
export type FasciaPart = { out0: number, out1: number, z0: number, z1: number, };
