// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreFeature } from "./CoreFeature";
import type { Discontinuity } from "./Discontinuity";
import type { LevelFeature } from "./LevelFeature";
import type { OpenZone } from "./OpenZone";
import type { Pt } from "./Pt";
import type { UseKind } from "./UseKind";
import type { WallFeature } from "./WallFeature";

/**
 * Everything the scoring reads, found deterministically from the model.
 */
export type Features = { 
/**
 * Levels with something built on them, lowest first.
 */
levels: Array<LevelFeature>, storyCount: number, 
/**
 * From the lowest level to the top of the highest walls, mm.
 */
totalHeight: number, 
/**
 * Overall plan extent, mm.
 */
min: Pt, max: Pt, 
/**
 * Long side over short side.
 */
aspectRatio: number, footprintArea: number, walls: Array<WallFeature>, cores: Array<CoreFeature>, openZones: Array<OpenZone>, discontinuities: Array<Discontinuity>, reentrantCorners: number, 
/**
 * The longest room span (short side of the largest room), mm: what joists between
 * bearing walls must reach.
 */
maxSpan: number, 
/**
 * The longest span a column-free room needs, mm (0 if none): what any scheme must reach.
 */
columnFreeSpan: number, 
/**
 * Uses across the building, most common first.
 */
uses: Array<UseKind>, 
/**
 * Upper levels' average wall stacking ratio.
 */
stacking: number, };
