// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Furniture, or equipment (appliances, mechanical, amenity and fitness equipment).
 */
export type FfeClass = "Furniture" | "Equipment";
