// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The shape a piece is built as.
 */
export type FfeKind = "Sofa" | "Sectional" | "Armchair" | "Chaise" | "Chair" | "Stool" | "OfficeChair" | "Ottoman" | "Bench" | "Booth" | "Table" | "RoundTable" | "Desk" | "Bed" | "BunkBed" | "Crib" | "Casegood" | "Cabinet" | "Wardrobe" | "Bookcase" | "Rug" | "LuggageRack" | "PoolTable" | "Umbrella" | "Refrigerator" | "Range" | "Cooktop" | "WallOven" | "Microwave" | "OtrMicrowave" | "Hood" | "Dishwasher" | "Washer" | "Dryer" | "StackedLaundry" | "WaterHeater" | "WallBox" | "Furnace" | "Condenser" | "MiniSplit" | "Ptac" | "Tv" | "WineCooler" | "IceMachine" | "Vending" | "ChestFreezer" | "CounterAppliance" | "Cart" | "Lockers" | "Mailboxes" | "Treadmill" | "Elliptical" | "Bike" | "WeightBench" | "Rack" | "Grill" | "Kiosk";
