// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FfePreset } from "./FfePreset";
import type { FfeUseOption } from "./FfeUseOption";

/**
 * The furniture or equipment library: its pieces, the picker's groups and the uses.
 */
export type FfeLibrary = { presets: Array<FfePreset>, groups: Array<string>, uses: Array<FfeUseOption>, };
