// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FfeSpec } from "./FfeSpec";
import type { FfeUse } from "./FfeUse";

/**
 * A library piece (a Revit family type).
 */
export type FfePreset = { name: string, description: string, group: string, uses: Array<FfeUse>, spec: FfeSpec, };
