// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FfeClass } from "./FfeClass";
import type { FfeKind } from "./FfeKind";
import type { FfeMount } from "./FfeMount";

/**
 * A furniture or equipment type's data (mm).
 */
export type FfeSpec = { class: FfeClass, kind: FfeKind, width: number, depth: number, height: number, mount: FfeMount, 
/**
 * The base's height above the floor, for wall and counter pieces.
 */
mount_height: number, 
/**
 * Seats, pillows, drawers, doors, burners, columns: the archetype's count.
 */
count: number, 
/**
 * Main and accent colors (sRGB).
 */
color: [number, number, number], accent: [number, number, number], 
/**
 * Seat and back cushions in their own fabric (outdoor wicker seating, ADR-095).
 */
cushion?: [number, number, number], };
