// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";

/**
 * What an FFE thumbnail shows: a project type, or a library piece by name.
 */
export type FfeSource = { "Type": ElementId } | { "Preset": string };
