// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FfeThumbPart } from "./FfeThumbPart";

/**
 * A piece by itself, for the picker: its triangles by color.
 */
export type FfeThumb = { parts: Array<FfeThumbPart>, };
