// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FfeUse } from "./FfeUse";

export type FfeUseOption = { id: FfeUse, label: string, };
