// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A filled region's pattern (Revit's drafting patterns), drawn at a paper size so it reads
 * the same at any scale.
 */
export type FillPattern = "Solid" | "Gray" | "Diagonal" | "CrossHatch" | "Concrete" | "Earth" | "Gravel" | "Sand" | "Masonry" | "RigidInsulation" | "Wood" | "Steel" | "Masking";
