// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A rendering finish for surfaces without a project material (ADR-095).
 */
export type Finish = "Fabric" | "Wicker" | "Wood" | "Stainless" | "Canvas" | "PowderCoat" | "Glass" | "Lacquer" | "Stone";
