// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrameFinish } from "./FrameFinish";

export type FinishOption = { id: FrameFinish, label: string, color: [number, number, number], };
