// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LightDistribution } from "./LightDistribution";
import type { LightFamily } from "./LightFamily";
import type { LightMount } from "./LightMount";
import type { LightShape } from "./LightShape";

/**
 * A lighting fixture type's data (mm, lumens, kelvin, watts, degrees).
 */
export type FixtureSpec = { family: LightFamily, mount: LightMount, 
/**
 * Body size: across, front to back (or the diameter, for round bodies) and tall.
 */
width: number, depth: number, height: number, 
/**
 * Suspension length from the ceiling (pendants), else 0.
 */
drop: number, 
/**
 * Default elevation for wall, floor and ground fixtures (the fixture's center on a
 * wall, the base on the floor).
 */
mount_height: number, 
/**
 * Initial intensity.
 */
lumens: number, watts: number, 
/**
 * Initial color: color temperature.
 */
kelvin: number, shape: LightShape, distribution: LightDistribution, 
/**
 * Spot beam (full) angle.
 */
beam: number, };
