// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A fixture by itself for the picker (at the origin; ceiling ones hung from z = 0).
 */
export type FixtureThumb = { body: Array<number>, lens: Array<number>, color: [number, number, number], glow: [number, number, number], };
