// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";

/**
 * What a fixture thumbnail shows: a project type, or a library fixture by name.
 */
export type FixtureSource = { "Type": ElementId } | { "Preset": string };
