// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FlagKind = "Transfer" | "SpanOutOfRange" | "NonStackingLateral" | "ColumnInRoom" | "LateralDirection" | "Torsion" | "Discontinuity" | "Foundation";
