// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { OpeningFlip } from "./OpeningFlip";
import type { Pt } from "./Pt";

/**
 * A flip control: the double arrow drawn at `at` along `dir`; clicking it flips the
 * opening's hand (left/right, along the wall) or facing (up/down, across it).
 */
export type FlipControl = { id: ElementId, flip: OpeningFlip, at: Pt, dir: Pt, };
