// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FormKind } from "./FormKind";
import type { SketchCurve } from "./SketchCurve";

/**
 * One form of an in-place element.
 */
export type Form = { kind: FormKind, 
/**
 * Extrusions: closed loops. Blends: the base loop. Sweeps: the path, in order.
 */
sketch: Array<Array<SketchCurve>>, 
/**
 * A void cuts the element's solid forms (extrusions only, for now).
 */
void: boolean, };
