// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SketchCurve } from "./SketchCurve";
import type { SweepProfile } from "./SweepProfile";

/**
 * How a form is made from its sketch. Heights are above the element's level (mm).
 */
export type FormKind = { "Extrusion": { start: number, end: number, } } | { "Blend": { base: number, top: number, top_sketch: Array<SketchCurve>, } } | { "Sweep": { elevation: number, profile: SweepProfile, } };
