// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FormKind } from "./FormKind";

/**
 * The form an in-place sketch makes (ADR-068), with the options bar's settings.
 */
export type FormDraft = { kind: FormKind, void: boolean, 
/**
 * The form being edited (Edit Sketch); None for a new one.
 */
index: number | null, 
/**
 * A blend's top is being sketched (its base is done).
 */
top: boolean, };
