// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Frame and sash finish of a window type (its colour in 3D and renderings).
 */
export type FrameFinish = "White" | "Almond" | "Bronze" | "Black" | "Wood";
