// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppState } from "./AppState";
import type { BuildReport } from "./BuildReport";

export type GenerateResult = { state: AppState | null, report: BuildReport, summary: string, };
