// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far along: planning (with what's arrived) or building.
 */
export type GenerateProgress = { phase: string, chars: number, stories: number, rooms: number, 
/**
 * The building's name, once Claude has written it.
 */
name: string | null, };
