// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReferenceImage } from "./ReferenceImage";

/**
 * What the owner asked for.
 */
export type GenerateInputs = { 
/**
 * "Single-family house", "Garden-style apartments", "Boutique hotel"…
 */
buildingType: string, stories: number, 
/**
 * Gross building area, square feet (optional).
 */
area: number | null, 
/**
 * Bedrooms (houses), units (multifamily) or keys (hotels) — see `building_type`.
 */
count: number | null, bathrooms: number | null, style: string, 
/**
 * "auto", "hip", "gable" or "flat".
 */
roof: string, fitLot: boolean, 
/**
 * Front, side and rear setbacks, feet.
 */
setbacks: [number, number, number], references: string, prompt: string, images: Array<ReferenceImage>, 
/**
 * "claude-opus-5-5" or "claude-sonnet-5-5".
 */
model: string, 
/**
 * An architect or work to design after (ADR-099), from the precedents or typed.
 */
precedent: string, 
/**
 * Landscape the site and furnish the rooms.
 */
landscape: boolean, 
/**
 * Lay out the CD set: plans, ceiling plans, elevations, sections, schedules.
 */
cdSet: boolean, };
