// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a room's outside walls are glazed (ADR-099).
 */
export type GlazingKind = "none" | "punched" | "large" | "ribbon" | "window_wall" | "sliding_doors" | "folding_doors";
