// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GrassKind } from "./GrassKind";
import type { GrassSpec } from "./GrassSpec";

/**
 * D5's grass kinds for the brush, each with its own look.
 */
export type GrassKindInfo = { kind: GrassKind, label: string, spec: GrassSpec, };
