// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a Grass-type material's blades grow (Enscape's Height and Height Variation).
 */
export type GrassSettings = { 
/**
 * Blade height (mm).
 */
height: number, 
/**
 * How much blades differ in height, 0 (all the same) to 1.
 */
variation: number, };
