// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GrassKind = "Lawn" | "LushLawn" | "Meadow" | "WildGrass" | "DryGrass" | "Clover" | "TallGrass";
