// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { GrassSpec } from "./GrassSpec";

/**
 * Each painted patch's grass, for growing its blades (those hidden in `view` left out).
 */
export type GrassPatchInfo = { el: ElementId, spec: GrassSpec, };
