// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GrassKind } from "./GrassKind";

/**
 * How painted grass grows.
 */
export type GrassSpec = { kind: GrassKind, 
/**
 * Blade height, mm.
 */
height: number, 
/**
 * 0 (even) to 1 (very uneven).
 */
variation: number, 
/**
 * Relative to the kind's natural density, 0.2 to 2.
 */
density: number, 
/**
 * sRGB.
 */
color: [number, number, number], };
