// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Grille (simulated divided lite) pattern of a window type.
 */
export type Grille = "None" | "Colonial" | "Prairie" | "Craftsman";
