// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { Pt } from "./Pt";

/**
 * A draggable point. Dragging it calls `drag_handle(id, key, to)`.
 */
export type Grip = { id: ElementId, key: string, at: Pt, 
/**
 * The fixed point a rubber-band line is drawn from while dragging, if any.
 */
anchor: Pt | null, };
