// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The Site & Landscape library materials for the ground picker.
 */
export type GroundChoice = { id: string, name: string, description: string, color: [number, number, number], texture: string | null, };
