// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { GroupKind } from "./GroupKind";

/**
 * A group type and how many instances it has.
 */
export type GroupTypeInfo = { id: ElementId, name: string, kind: GroupKind, instances: number, };
