// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { GroupKind } from "./GroupKind";
import type { Pt } from "./Pt";

/**
 * One group instance, as the app shows it.
 */
export type GroupInfo = { id: ElementId, typeId: ElementId, name: string, kind: GroupKind, members: Array<ElementId>, origin: Pt, level: ElementId | null, view: ElementId | null, };
