// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Grip } from "./Grip";
import type { TempDim } from "./TempDim";

export type Handles = { grips: Array<Grip>, dims: Array<TempDim>, };
