// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppState } from "./AppState";
import type { ImportReport } from "./ImportReport";

/**
 * An IFC import's new project and what came in (ADR-035).
 */
export type IfcImported = { state: AppState | null, report: ImportReport, };
