// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pt } from "./Pt";

/**
 * A satellite image covering the site (ADR-026): what to ask Google's Static Maps for, and
 * where the image's corners fall in the project.
 */
export type ImageryFrame = { 
/**
 * Image center.
 */
lat: number, lon: number, 
/**
 * Web Mercator zoom level.
 */
zoom: number, 
/**
 * Size in map pixels (the image is fetched at twice this).
 */
width: number, height: number, 
/**
 * The image's corners in project plan coordinates (mm): lower left, lower right, upper
 * right, upper left.
 */
corners: [Pt, Pt, Pt, Pt], };
