// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What came in, and what didn't.
 */
export type ImportReport = { schema: string, 
/**
 * The authoring tool, from the file header.
 */
application: string, project: string, levels: number, walls: number, doors: number, windows: number, floors: number, roofs: number, rooms: number, grids: number, columns: number, 
/**
 * Kinds of product not brought in, with counts (stairs, curtain walls, furniture…).
 */
skipped: Array<[string, number]>, warnings: Array<string>, };
