// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";

/**
 * A row of the sheet index: a sheet (`sheet` set), a new sheet to make (neither set), or a
 * placeholder.
 */
export type IndexRow = { sheet: ElementId | null, number: string, name: string, placeholder: boolean, };
