// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";

/**
 * An issue the index can show the sheet list of (ADR-116): a phase's deliverable, with the
 * stage whose set it is. The CD phase issues at 50%, 90% and 100% and for permit, all from
 * the CD stage's set.
 */
export type IndexIssue = { key: string, label: string, 
/**
 * The stage's abbreviation (SD, DD, CD…).
 */
phase: string, stage: ElementId, };
