// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";
import type { ElementId } from "./ElementId";

/**
 * The editor, for the UI.
 */
export type InPlaceInfo = { id: ElementId, name: string, category: Category, categoryLabel: string, 
/**
 * Its forms, numbered by kind ("Extrusion 1", "Void Extrusion 1").
 */
forms: Array<string>, isNew: boolean, };
