// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { Prim } from "./Prim";

export type Item = { 
/**
 * Source element, used for selection and highlighting.
 */
el: ElementId | null, prim: Prim, };
