// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the project is permitted: the code family and local requirements that shape the
 * general sheets.
 */
export type Jurisdiction = "ModelCodes" | "California" | "NewYorkCity" | "Florida" | "Texas" | "Washington" | "Massachusetts" | "Chicago";
