// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";

/**
 * Where a tag's keynote comes from.
 */
export type KeynoteSource = { "Element": { target: ElementId, } } | { "Material": { target: ElementId, material: ElementId, } } | { "User": { key: string, } };
