// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Assignable } from "./Assignable";
import type { ElementId } from "./ElementId";

/**
 * What an Element or Material keynote would tag on `id`: its type and materials with their
 * keynotes.
 */
export type KeynoteTarget = { id: ElementId, typeId?: ElementId, typeName: string, typeKey?: string, materials: Array<Assignable>, };
