// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How tags number: by their keynote ("09 29 00.A1"), or 1, 2, 3… on each sheet.
 */
export type KeynoteNumbering = "ByKeynote" | "BySheet";
