// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Keynote } from "./Keynote";
import type { KeynoteNumbering } from "./KeynoteNumbering";
import type { KeynoteUse } from "./KeynoteUse";

/**
 * The Keynote Manager's table: the keynotes in key order, the numbering, and where each is
 * used.
 */
export type KeynoteTableInfo = { entries: Array<Keynote>, numbering: KeynoteNumbering, usage: Array<KeynoteUse>, };
