// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where each keynote is used: tags and assigned types/materials.
 */
export type KeynoteUse = { key: string, tags: number, assigned: Array<string>, };
