// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The lateral system a scheme uses.
 */
export type LateralKind = "WoodShearWalls" | "CfsShearWalls" | "ConcreteShearWalls" | "BracedFrames" | "MomentFrames" | "CltShearWalls";
