// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a wall layer does (Revit's layer functions).
 */
export type LayerFunction = "Structure" | "Substrate" | "Insulation" | "Finish" | "Membrane" | "AirGap";
