// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pt } from "./Pt";

/**
 * Revit's leader shapes: one segment, two segments (with an elbow) or an arc.
 */
export type Leader = { 
/**
 * The arrowhead's point.
 */
end: Pt, 
/**
 * Two segments: the elbow between the text and the arrowhead.
 */
elbow: Pt | null, 
/**
 * Curved (Revit's arc leader).
 */
arc: boolean, };
