// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a door leaf looks like.
 */
export type LeafStyle = "Flush" | "SixPanel" | "Shaker" | "FivePanel" | "Craftsman" | "FullLite" | "HalfLite" | "FifteenLite" | "VisionLite" | "Louvered" | "BarnX";
