// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { Pt } from "./Pt";
import type { UseKind } from "./UseKind";

/**
 * One level of the building.
 */
export type LevelFeature = { id: ElementId, name: string, 
/**
 * mm.
 */
elevation: number, 
/**
 * To the next level up (or the tops of this level's walls at the roof), mm.
 */
floorToFloor: number, 
/**
 * Its floor outline (the largest floor on it), or its walls' extent; mm.
 */
outline: Array<Pt>, 
/**
 * mm².
 */
area: number, wallLength: number, exteriorWallLength: number, 
/**
 * Share of this level's wall length standing on walls of the level below (1 at the
 * bottom).
 */
stackingRatio: number, 
/**
 * Main uses on this level, from its rooms' names.
 */
uses: Array<UseKind>, 
/**
 * Its longest clear span: the short side of its largest room, mm.
 */
maxRoomSpan: number, };
