// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Revit's "Emit from Shape".
 */
export type LightShape = "Point" | "Line" | "Rectangle" | "Circle";
