// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the fixture is placed (Revit hosts: ceiling face, suspended, wall face, floor or
 * the ground).
 */
export type LightMount = "Ceiling" | "Pendant" | "Wall" | "Floor" | "Ground";
