// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LightPreset } from "./LightPreset";
import type { UseOption } from "./UseOption";

/**
 * The lighting library: its fixtures, the picker's groups and the building types.
 */
export type LightLibrary = { presets: Array<LightPreset>, groups: Array<string>, uses: Array<UseOption>, };
