// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Revit's light distribution (photometric webs aren't supported).
 */
export type LightDistribution = "Spherical" | "Hemispherical" | "Spot";
