// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The fixture's body, as studio-views draws it in plan and 3D.
 */
export type LightFamily = "Downlight" | "Gimbal" | "Troffer" | "FlatPanel" | "FlushMount" | "CeilingFan" | "TrackLight" | "DrumPendant" | "GlobePendant" | "MiniPendant" | "Chandelier" | "LinearPendant" | "LinearSlot" | "StripLight" | "UnderCabinet" | "CoveLight" | "WallSconce" | "VanityLight" | "WallWasher" | "FloorLamp" | "TableLamp" | "HighBay" | "ExitSign" | "EmergencyLight" | "WallPack" | "Lantern" | "Bollard" | "AreaPole" | "PostTop" | "FloodLight" | "InGrade" | "StepLight" | "LandscapeSpot";
