// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingUse } from "./BuildingUse";
import type { FixtureSpec } from "./FixtureSpec";

/**
 * A library fixture (a Revit family type).
 */
export type LightPreset = { name: string, description: string, group: string, uses: Array<BuildingUse>, spec: FixtureSpec, };
