// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { LightDistribution } from "./LightDistribution";
import type { LightShape } from "./LightShape";

/**
 * One fixture's light, for renders (mm, z up).
 */
export type LightInfo = { el: ElementId, type_id: ElementId, level: ElementId, 
/**
 * Where the light leaves the fixture (the lens), and which way it points.
 */
at: [number, number, number], dir: [number, number, number], 
/**
 * The emitting shape's long axis in plan, and its size (width, length) in mm.
 */
axis: [number, number], size: [number, number], shape: LightShape, distribution: LightDistribution, 
/**
 * Initial intensity times the dimming.
 */
lumens: number, color: [number, number, number], 
/**
 * Spot beam (full) angle, degrees.
 */
beam: number, on: boolean, dimming: number, exterior: boolean, };
