// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Revit's default line styles.
 */
export type LineStyle = "Thin" | "Medium" | "Wide" | "Hidden" | "Centerline" | "Overhead" | "Demolished" | "Beyond";
