// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppState } from "./AppState";
import type { ElementId } from "./ElementId";

export type LoadedWindows = { state: AppState | null, 
/**
 * The type for each spec, in order.
 */
ids: Array<ElementId>, };
