// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which line of a wall its drawn points follow (Revit's Location Line). The wall is
 * stored by its centerline; the location line decides how drawn points map to it.
 */
export type LocationLine = "Centerline" | "CoreCenterline" | "FinishExterior" | "FinishInterior" | "CoreExterior" | "CoreInterior";
