// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an elevation mark is drawn (the symbol of its family type, ADR-022).
 */
export type MarkStyle = "CircleArrow" | "CircleHalf" | "Diamond";
