// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Library preset ids (ADR-029) for the building's main surfaces.
 */
export type MaterialSpec = { exteriorWalls: string | null, interiorWalls: string | null, floors: string | null, roof: string | null, };
