// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A member of the layout.
 */
export type MemberKind = "Column" | "Girder" | "Beam" | "BearingWall" | "ShearWall" | "BracedFrame" | "MomentFrame" | "Span" | "Transfer" | "SpreadFooting" | "StripFooting" | "Mat" | "PileCap" | "FoundationWall";
