// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The site's climate, as the user sets it (for mechanical systems).
 */
export type MepClimate = "Hot" | "Mixed" | "Cold";
