// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { Pt } from "./Pt";

/**
 * An exterior wall, with the direction that points outside.
 */
export type MepExteriorWall = { level: ElementId, start: Pt, end: Pt, thickness: number, outward: Pt, };
