// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { MepDoor } from "./MepDoor";
import type { MepExteriorWall } from "./MepExteriorWall";
import type { MepLevel } from "./MepLevel";
import type { MepSpace } from "./MepSpace";
import type { Pt } from "./Pt";

/**
 * The building, as the MEP suggestions read it.
 */
export type MepFeatures = { levels: Array<MepLevel>, spaces: Array<MepSpace>, exteriorWalls: Array<MepExteriorWall>, exteriorDoors: Array<MepDoor>, 
/**
 * Stair and shaft extents per level (vertical routes).
 */
cores: Array<[ElementId, Pt, Pt]>, stories: number, 
/**
 * Floor area of all levels, mm².
 */
area: number, min: Pt, max: Pt, 
/**
 * Uses by floor area, largest first ("residential", "office"…).
 */
uses: Array<string>, 
/**
 * Kitchens in residential buildings: one per dwelling.
 */
dwellingUnits: number, residential: boolean, };
