// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { MepKind } from "./MepKind";
import type { Pt } from "./Pt";

/**
 * A placed item: a point device (one point) or a run (a polyline), on `level`, from
 * elevation `base` to `top` (mm).
 */
export type MepItem = { kind: MepKind, level: ElementId, pts: Array<Pt>, base: number, top: number, 
/**
 * Preliminary size or rating, e.g. "3-ton condenser (prelim.)".
 */
size: string, 
/**
 * Plan width of a run (duct width, tray width), mm; 0 for a line.
 */
width: number, 
/**
 * The rule that placed and sized it.
 */
rule: string, };
