// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Every kind of item the four layers place.
 */
export type MepKind = "Equipment" | "OutdoorUnit" | "IndoorUnit" | "Diffuser" | "ReturnGrille" | "SupplyDuct" | "Refrigerant" | "Piping" | "Shaft" | "Service" | "Panel" | "Transformer" | "Generator" | "Feeder" | "Light" | "Receptacle" | "WaterService" | "WaterHeater" | "Fixture" | "Stack" | "BuildingDrain" | "ColdWater" | "HotWater" | "Vent" | "Mdf" | "Idf" | "Pathway" | "Backbone" | "DataOutlet" | "AccessPoint" | "Camera" | "AccessControl" | "AvDisplay";
