// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { MepLayout } from "./MepLayout";
import type { MepSettings } from "./MepSettings";

/**
 * A discipline's layer, for exports and the panel.
 */
export type MepLayer = { id: ElementId, settings: MepSettings, layout: MepLayout, disclaimer: string, };
