// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MepFlag } from "./MepFlag";
import type { MepItem } from "./MepItem";
import type { MepZone } from "./MepZone";

export type MepLayout = { items: Array<MepItem>, zones: Array<MepZone>, flags: Array<MepFlag>, 
/**
 * Whole-building numbers and notes (loads, service size, fixture units).
 */
notes: Array<string>, };
