// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { Pt } from "./Pt";

export type MepLevel = { id: ElementId, name: string, elevation: number, 
/**
 * The next level up, or the top of its walls.
 */
top: number, outline: Array<Pt>, area: number, };
