// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Discipline } from "./Discipline";
import type { MepClimate } from "./MepClimate";
import type { SystemProposal } from "./SystemProposal";

/**
 * A discipline's Suggest answer: every system ranked, best first.
 */
export type MepProposal = { discipline: Discipline, disclaimer: string, climate: MepClimate, systems: Array<SystemProposal>, assumptions: Array<string>, questions: Array<string>, summary: Array<string>, };
