// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Discipline } from "./Discipline";
import type { MepClimate } from "./MepClimate";

/**
 * What the user picked before generating.
 */
export type MepSettings = { discipline: Discipline, 
/**
 * The system's key in the rules file, e.g. "vrf_doas".
 */
system: string, climate: MepClimate, };
