// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { Pt } from "./Pt";

/**
 * A room read for MEP: its type from its name, size, and whether it touches the outside.
 */
export type MepSpace = { id: ElementId, level: ElementId, name: string, 
/**
 * The space type from the rules (Bedroom, Restroom, Office…).
 */
kind: string, ring: Array<Pt>, min: Pt, max: Pt, center: Pt, 
/**
 * mm².
 */
area: number, 
/**
 * Length of its edges on exterior walls, mm, and the longest such edge.
 */
exteriorLen: number, exteriorEdge?: [Pt, Pt], };
