// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { Pt } from "./Pt";

/**
 * A zone (thermal zone, circuit area, coverage cell) drawn as a tinted area.
 */
export type MepZone = { level: ElementId, ring: Array<Pt>, label: string, };
