// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";
import type { ElementId } from "./ElementId";

export type Mesh = { el: ElementId, category: Category, 
/**
 * Exterior walls render in a different tone.
 */
exterior: boolean, 
/**
 * Shaded color from the element's material (ADR-020), when it has one.
 */
color: [number, number, number] | null, 
/**
 * Triangle soup, 9 floats per triangle, mm, z-up.
 */
positions: Array<number>, };
