// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanOp } from "./PlanOp";

/**
 * Claude's plan: the operations, a one-line summary, or why it can't be done.
 */
export type ModelPlan = { operations: Array<PlanOp>, summary: string, message: string, };
