// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What Claude proposes.
 */
export type ModelEdit = { 
/**
 * `set_parameter`, `resize_building`, or `none` (with `message` saying why).
 */
action: string, 
/**
 * Walls, Doors, Windows, Floors, Ceilings, Roofs, Rooms, Columns, Beams, Railings,
 * Stairs, Levels or Grids.
 */
category: string, 
/**
 * A property as Properties names it: "Width", "Unconnected Height", "Sill Height"…
 */
parameter: string, 
/**
 * The new value: `3'-0"`, a type name, a choice's label.
 */
value: string, 
/**
 * `model`, `level`, `selection` or `view`.
 */
scope: string, 
/**
 * The level's name, for `level` scope.
 */
level: string, 
/**
 * Only elements whose type name contains this (e.g. "Single").
 */
typeFilter: string, 
/**
 * For `resize_building`: `east-west` (width) or `north-south` (depth).
 */
axis: string, 
/**
 * For `resize_building`: the side that stays put — `west`, `east`, `south`, `north`
 * or `center`.
 */
anchor: string, 
/**
 * One line: "Width → 3'-0" on 7 doors".
 */
summary: string, 
/**
 * For `none`: why the request can't be done.
 */
message: string, };
