// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A property to set, by the name Properties shows.
 */
export type NameValue = { name: string, value: string, };
