// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotesBuilding } from "./NotesBuilding";
import type { NotesDrawing } from "./NotesDrawing";

/**
 * What the General Notes dialog offers: the building types and drawings, the defaults for
 * the view (from Project Info and the view itself) and the code edition.
 */
export type NotesOptions = { buildings: Array<[NotesBuilding, string]>, drawings: Array<[NotesDrawing, string]>, building: NotesBuilding, drawing: NotesDrawing, code: string, };
