// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The drawings notes are written for.
 */
export type NotesDrawing = "General" | "SitePlan" | "FloorPlan" | "CeilingPlan" | "RoofPlan" | "Elevations" | "Sections" | "Details" | "EnlargedPlans" | "Schedules";
