// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The building types notes are tailored to.
 */
export type NotesBuilding = "SingleFamily" | "DuplexTownhouse" | "Multifamily" | "MixedUse" | "Hotel" | "Commercial";
