// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { Item } from "./Item";

/**
 * What Offset would create for the cursor at `p`: the line `distance` mm from the wall
 * or grid under the cursor, on the cursor's side.
 */
export type OffsetPreview = { id: ElementId, items: Array<Item>, };
