// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OpeningThumb = { 
/**
 * Frame, casing, sashes and leaves (9 floats a triangle, mm, z-up).
 */
frame: Array<number>, glass: Array<number>, wall: Array<number>, 
/**
 * The finish colour.
 */
color: [number, number, number], };
