// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpeningPreview } from "./OpeningPreview";

/**
 * A door or window placed from the 3D view (ADR-022): where it would go in `host` for a
 * hit at plan point `p`, and its box as triangles for the ghost preview.
 */
export type OpeningPreview3d = { preview: OpeningPreview, positions: Array<number>, };
