// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { Pt } from "./Pt";

/**
 * A room wanting a long clear span.
 */
export type OpenZone = { room: ElementId, name: string, level: ElementId, 
/**
 * mm².
 */
area: number, 
/**
 * Short side of its extent, mm.
 */
span: number, center: Pt, 
/**
 * Must be column-free (assembly, gym…); retail and parking take columns on a grid.
 */
columnFree: boolean, };
