// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a door or window flips: Revit's two flip controls, or the spacebar's cycle.
 */
export type OpeningFlip = "Hand" | "Facing" | "Cycle";
