// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { Item } from "./Item";

export type OpeningPreview = { host: ElementId, 
/**
 * Center distance from the host's start, mm.
 */
offset: number, flipFacing: boolean, 
/**
 * False when the opening would overlap another one in the wall.
 */
valid: boolean, 
/**
 * Distances from the opening's edges to the wall ends.
 */
label: string, items: Array<Item>, };
