// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverlayKind } from "./OverlayKind";

/**
 * A 3D piece: a triangle soup (9 floats per triangle, mm, z up).
 */
export type OverlayMesh = { kind: OverlayKind, member?: number, flag?: number, positions: Array<number>, };
