// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverlayKind } from "./OverlayKind";

/**
 * One piece of the plan overlay, in model mm.
 */
export type OverlayPrim = { kind: OverlayKind, 
/**
 * Index into the layout's members or flags.
 */
member?: number, flag?: number, 
/**
 * Filled areas.
 */
fill: Array<Array<[number, number]>>, 
/**
 * Lines.
 */
lines: Array<Array<[number, number]>>, 
/**
 * A label and where it goes, paper mm high.
 */
label?: [string, [number, number]], };
