// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverlayKind } from "./OverlayKind";

/**
 * What hovering or clicking an overlay piece shows.
 */
export type OverlayInfo = { kind: OverlayKind, title: string, lines: Array<string>, };
