// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an overlay piece is (its colour on the canvas).
 */
export type OverlayKind = "Grid" | "Column" | "Girder" | "Beam" | "BearingWall" | "ShearWall" | "BracedFrame" | "MomentFrame" | "Span" | "Transfer" | "Flag" | "Mep" | "MepZone";
