// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a project parameter belongs to each instance or to its type.
 */
export type ParamScope = "Instance" | "Type";
