// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A parameter value. Lengths are mm, areas mm², angles radians.
 */
export type ParamValue = { "kind": "Length", "value": number } | { "kind": "Area", "value": number } | { "kind": "Angle", "value": number } | { "kind": "Number", "value": number } | { "kind": "Integer", "value": number } | { "kind": "Bool", "value": boolean } | { "kind": "Text", "value": string };
