// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";
import type { ParamKind } from "./ParamKind";
import type { ParamScope } from "./ParamScope";

/**
 * A user-defined project parameter, stored on the project information element.
 */
export type ParamDef = { 
/**
 * Stable key in element parameter maps.
 */
key: string, label: string, kind: ParamKind, scope: ParamScope, 
/**
 * Instance categories it applies to (for type parameters, the instances' category).
 */
categories: Array<Category>, };
