// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of value a parameter holds.
 */
export type ParamKind = "Length" | "Area" | "Angle" | "Number" | "Integer" | "Bool" | "Text";
