// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A parcel from Regrid: its boundary as [lat, lon] pairs and its record.
 */
export type ParcelHit = { ring: Array<[number, number]>, apn: string, owner: string, address: string, acres: number, };
