// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the parcel data says about the lot.
 */
export type ParcelInfo = { 
/**
 * Assessor's parcel number.
 */
apn: string, owner: string, address: string, acres: number, 
/**
 * Where the boundary came from, e.g. "Regrid".
 */
source: string, };
