// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";

/**
 * One step of Revit's Tab selection: the elements it would select and the status bar's
 * name for them.
 */
export type PickCandidate = { ids: Array<ElementId>, label: string, };
