// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A sheet listed in the sheet index that isn't in the project, as Revit's placeholder
 * sheets: a consultant's sheet, or one drawn elsewhere.
 */
export type PlaceholderSheet = { number: string, name: string, };
