// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Climate } from "./Climate";
import type { PlantSpec } from "./PlantSpec";

/**
 * An Asset Library entry.
 */
export type PlantPreset = { name: string, 
/**
 * The species' name without its season, grouping its variants.
 */
species: string, description: string, climates: Array<Climate>, spec: PlantSpec, };
