// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Trees and shrubs for the site (ADR-099), by Asset Library name.
 */
export type PlantingSpec = { trees: Array<string>, shrubs: Array<string>, };
