// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlanOpening = { 
/**
 * The opening's center, pixels.
 */
at: [number, number], 
/**
 * Inches.
 */
width: number, height: number, 
/**
 * Windows: sill above the floor, inches.
 */
sill: number, 
/**
 * swing, double, sliding, pocket, bifold, garage, french (doors); fixed, casement,
 * double_hung, slider, awning (windows).
 */
kind: string, };
