// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The Asset Library's groups.
 */
export type PlantGroup = "Deciduous" | "Flowering" | "Evergreen" | "Conifer" | "Palm" | "Shrub" | "Hedge" | "Grass" | "Perennial" | "Succulent";
