// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlannedSheet = { number: string, name: string, discipline: string, 
/**
 * What goes on it: the views and their scale, or who provides it.
 */
contents: string, placeholder: boolean, 
/**
 * Stage abbreviations whose sets include it.
 */
phases: Array<string>, 
/**
 * A sheet with this number is already in the project.
 */
exists: boolean, };
