// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bark } from "./Bark";
import type { CrownForm } from "./CrownForm";
import type { Foliage } from "./Foliage";
import type { PlantGroup } from "./PlantGroup";
import type { Season } from "./Season";

/**
 * A species and how it looks (mm, sRGB colours).
 */
export type PlantSpec = { botanical: string, group: PlantGroup, form: CrownForm, foliage: Foliage, bark_kind: Bark, 
/**
 * Overall height and crown spread.
 */
height: number, spread: number, 
/**
 * A clipped hedge's depth across (its spread is its length); 0 otherwise.
 */
depth: number, 
/**
 * Clear trunk up to the lowest branches.
 */
trunk: number, 
/**
 * Trunk diameter at the base.
 */
caliper: number, 
/**
 * Trunks (multi-stem) or, for shrubs and grasses, main stems.
 */
stems: number, leaf: [number, number, number], leaf_alt: [number, number, number], bark: [number, number, number], flowers?: [number, number, number], autumn?: [number, number, number], season: Season, 
/**
 * How full the crown is, 0.2 (open) to 1 (dense).
 */
density: number, };
