// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of a plant's textures.
 */
export type PlantMap = "Foliage" | "Bark" | "BarkNormal";
