// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlannedDeliverable = { phase: string, stage: string, 
/**
 * Rufplan catalog id (sd100, permit, bid…).
 */
id: string, name: string, sheets: Array<string>, };
