// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One plan sheet as sent: the image and what the owner says it is.
 */
export type PlanImage = { mediaType: string, 
/**
 * Base64.
 */
data: string, 
/**
 * Pixel size of the image as sent.
 */
width: number, height: number, 
/**
 * The owner's label ("First Floor"); may be empty.
 */
level: string, 
/**
 * Floor elevation in feet if the owner knows it.
 */
elevation: number | null, };
