// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanImage } from "./PlanImage";

export type PlansInputs = { name: string, sheets: Array<PlanImage>, 
/**
 * Scale, heights, anything that helps read the drawings.
 */
notes: string, model: string, };
