// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";

/**
 * A plant to show: a project type, or a library asset by name.
 */
export type PlantSource = { "Type": ElementId } | { "Preset": string };
