// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlanReport = { name: string, levels: number, walls: number, doors: number, windows: number, rooms: number, floors: number, roofs: number, warnings: Array<string>, };
