// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pt } from "./Pt";

/**
 * One plant to place: where, turned how far and how big.
 */
export type PlantAt = { at: Pt, rotation: number, scale: number, };
