// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";

/**
 * Where each planting is, for drawing the full models (Realistic views and renders).
 */
export type PlantInstance = { el: ElementId, type_id: ElementId, variant: number, 
/**
 * A hash of its type's spec: a changed type is grown again.
 */
spec_key: string, 
/**
 * The base (project mm, z up).
 */
at: [number, number, number], rotation: number, scale: number, };
