// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A point in feet. In an elevation or section, a plan point with a height `z` lands where
 * the view shows it.
 */
export type PlanPoint = { x: number, y: number, z: number | null, };
