// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NameValue } from "./NameValue";
import type { PlanPoint } from "./PlanPoint";

/**
 * One operation. Only the fields its `op` uses matter.
 */
export type PlanOp = { op: string, 
/**
 * A name for what this makes, to refer to later as `$name`.
 */
as: string, id: string, ids: Array<string>, category: string, parameter: string, value: string, scope: string, typeFilter: string, axis: string, anchor: string, level: string, topLevel: string, type: string, from: string, start: PlanPoint | null, end: PlanPoint | null, at: PlanPoint | null, center: PlanPoint | null, a: PlanPoint | null, b: PlanPoint | null, points: Array<PlanPoint>, wall: string, 
/**
 * Feet along a wall from its start, a dimension's offset, a roof's overhang…
 */
offset: number | null, flip: boolean, height: string, width: string, elevation: string, slope: string, name: string, number: string, text: string, view: string, sheet: string, byWalls: boolean, dx: number, dy: number, angle: number, count: number, 
/**
 * A material by name (the project's, or the library's), for paint.
 */
material: string, 
/**
 * A colour "#rrggbb" for a new material.
 */
color: string, properties: Array<NameValue>, };
