// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanSheet } from "./PlanSheet";

export type PlanSet = { name: string, summary: string, sheets: Array<PlanSheet>, 
/**
 * hip, gable or flat.
 */
roof: string, };
