// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Indexed triangles with normals, texture coordinates and a colour tint per vertex.
 */
export type PlantPart = { positions: Array<number>, normals: Array<number>, uvs: Array<number>, 
/**
 * Linear 0..1 (occlusion and variation baked in).
 */
colors: Array<number>, indices: Array<number>, };
