// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlanWall = { 
/**
 * Centerline ends, pixels.
 */
a: [number, number], b: [number, number], 
/**
 * Inches.
 */
thickness: number, exterior: boolean, };
