// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanOpening } from "./PlanOpening";
import type { PlanRoom } from "./PlanRoom";
import type { PlanWall } from "./PlanWall";

/**
 * One plan sheet as Claude read it. Points are image pixels: x right, y down.
 */
export type PlanSheet = { 
/**
 * The level this plan shows ("First Floor").
 */
level: string, 
/**
 * Floor elevation, feet, relative to the lowest floor (0).
 */
elevation: number, 
/**
 * Wall height on this floor, feet.
 */
wallHeight: number, 
/**
 * Image pixels per foot of the drawing, from its scale bar or a dimension string.
 */
pixelsPerFoot: number, 
/**
 * A point shared by every sheet (a corner, column or stair that stacks), in this
 * image's pixels, and where it is on the common grid, in feet.
 */
anchorPx: [number, number], anchorFt: [number, number], walls: Array<PlanWall>, doors: Array<PlanOpening>, windows: Array<PlanOpening>, rooms: Array<PlanRoom>, 
/**
 * Floor slab outlines (rooms and terraces), polygons in pixels.
 */
slabs: Array<Array<[number, number]>>, };
