// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlanRoom = { name: string, 
/**
 * A point inside the room, pixels.
 */
at: [number, number], };
