// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppState } from "./AppState";
import type { PlanReport } from "./PlanReport";

export type PlansResult = { state: AppState | null, report: PlanReport, summary: string, };
