// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Climate } from "./Climate";
import type { PlantGroup } from "./PlantGroup";
import type { PlantPreset } from "./PlantPreset";

/**
 * The library's shape for the Asset Library window.
 */
export type PlantLibrary = { presets: Array<PlantPreset>, 
/**
 * (group, its label, its Enscape category).
 */
groups: Array<[PlantGroup, string, string]>, climates: Array<[Climate, string]>, };
