// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlantPart } from "./PlantPart";

/**
 * A species' 3D model, base at the origin (mm, z up).
 */
export type PlantModel = { 
/**
 * Trunk and branches, textured with the bark (u around, v along; 1 = one tile).
 */
bark: PlantPart, 
/**
 * Leaf, needle, frond and flower cards: alpha-cut, textured with the foliage atlas
 * (2 × 2 cells).
 */
leaves: PlantPart, 
/**
 * Untextured solid parts (grass blades, agave leaves, cacti), coloured per vertex (sRGB
 * colour times the tint).
 */
solid: PlantPart, height: number, spread: number, };
