// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An architect or work to design after.
 */
export type Precedent = { name: string, 
/**
 * "Architect" or "Work".
 */
group: string, 
/**
 * The moves, in the plan's terms.
 */
moves: string, };
