// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which wall line a pick inside a wall takes when the cursor isn't at a face (Revit's
 * "Prefer" option).
 */
export type Prefer = "WallCenterlines" | "WallFaces" | "CenterOfCore" | "FacesOfCore";
