// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Appearance } from "./Appearance";
import type { Tier } from "./Tier";

/**
 * A library material.
 */
export type Preset = { id: string, name: string, category: string, tier: Tier, residential: boolean, hospitality: boolean, multifamily: boolean, 
/**
 * What it is and where it's typically used.
 */
description: string, 
/**
 * Shading colour for plans, elevations and the 3D view (sRGB).
 */
color: [number, number, number], 
/**
 * Surface pattern preset id for elevations.
 */
surface: string, appearance: Appearance, };
