// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A key date: "Permit submission", "Bid date", "Substantial completion"…
 */
export type ProjectMilestone = { name: string, 
/**
 * ISO date (YYYY-MM-DD), or empty.
 */
date: string, done: boolean, };
