// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A person or firm and how to reach them.
 */
export type ProjectContact = { company: string, name: string, title: string, email: string, phone: string, address: string, website: string, };
