// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectLocation = { street: string, city: string, state: string, zip: string, county: string, country: string, 
/**
 * Assessor's parcel number.
 */
apn: string, legal: string, 
/**
 * The authority having jurisdiction (the building department).
 */
jurisdiction: string, };
