// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A budget line. `hard` lines are construction cost; the rest are soft costs.
 */
export type ProjectBudgetLine = { name: string, hard: boolean, amount: number, notes: string, };
