// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The title block's fields, kept on the ProjectInfo element.
 */
export type ProjectIdentity = { name: string, number: string, client: string, address: string, };
