// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectOverview = { 
/**
 * "Active", "On Hold", "Complete"…
 */
status: string, 
/**
 * "Single-Family Residential", "Office", "Mixed-Use"…
 */
project_type: string, 
/**
 * "New Construction", "Addition", "Renovation"…
 */
work_type: string, 
/**
 * "Design-Bid-Build", "CM at Risk", "Design-Build"…
 */
delivery: string, description: string, 
/**
 * The program's target gross area, sf (0: not set).
 */
target_area_sf: number, };
