// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A design stage, as the Schedule section lists it.
 */
export type ProjectStageRow = { name: string, abbreviation: string, start: string, target: string, current: boolean, };
