// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectBudgetLine } from "./ProjectBudgetLine";

export type ProjectBudget = { currency: string, lines: Array<ProjectBudgetLine>, 
/**
 * Design and construction contingency, percent of the lines.
 */
contingency_pct: number, 
/**
 * Escalation to the midpoint of construction, percent of the hard cost.
 */
escalation_pct: number, 
/**
 * The owner's target construction cost per sf (0: not set).
 */
target_cost_sf: number, };
