// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectBudgetTotals } from "./ProjectBudgetTotals";
import type { ProjectDetails } from "./ProjectDetails";
import type { ProjectIdentity } from "./ProjectIdentity";
import type { ProjectSiteInfo } from "./ProjectSiteInfo";
import type { ProjectStageRow } from "./ProjectStageRow";

/**
 * Everything the Project Info tab shows.
 */
export type ProjectInfoState = { identity: ProjectIdentity, details: ProjectDetails, 
/**
 * From the model: gross area (outside faces of walls) and room area, sf.
 */
grossSf: number, roomSf: number, 
/**
 * The budget's sums, with the hard cost per gross sf.
 */
totals: ProjectBudgetTotals, levels: number, rooms: number, stages: Array<ProjectStageRow>, site: ProjectSiteInfo | null, 
/**
 * The linked Rufplan project's name (ADR-016).
 */
rufplan: string | null, disciplines: Array<string>, milestoneNames: Array<string>, };
