// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the UI needs to show about the open project.
 */
export type ProjectStatus = { 
/**
 * File name without extension, or "Untitled" before the first save.
 */
name: string, 
/**
 * Absolute path, or `null` before the first save.
 */
path: string | null, schemaVersion: number, 
/**
 * App version that last saved the file.
 */
appVersion: string, };
