// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectCodes = { 
/**
 * "2021 IBC", "2021 IRC"…
 */
building_code: string, energy_code: string, 
/**
 * IBC occupancy group: "R-3", "B", "A-2"…
 */
occupancy: string, 
/**
 * IBC construction type: "V-B", "III-A"…
 */
construction_type: string, sprinklered: string, zoning_district: string, lot_area: string, far: string, max_height: string, setbacks: string, lot_coverage: string, parking: string, notes: string, };
