// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectContact } from "./ProjectContact";

/**
 * One discipline on the team: its consultant, their scope and fee.
 */
export type ProjectTeamMember = { 
/**
 * "Architect", "Structural Engineer", "Civil Engineer"…
 */
discipline: string, contact: ProjectContact, scope: string, 
/**
 * Fee, in the budget's currency (0: not set).
 */
fee: number, notes: string, };
