// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The lot, from the Site tab (ADR-023), when there is one.
 */
export type ProjectSiteInfo = { address: string, lat: number, lon: number, apn: string, owner: string, acres: number, };
