// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectBudget } from "./ProjectBudget";
import type { ProjectCodes } from "./ProjectCodes";
import type { ProjectContact } from "./ProjectContact";
import type { ProjectLocation } from "./ProjectLocation";
import type { ProjectMilestone } from "./ProjectMilestone";
import type { ProjectOverview } from "./ProjectOverview";
import type { ProjectTeamMember } from "./ProjectTeamMember";

/**
 * Everything about the job, beside the model.
 */
export type ProjectDetails = { overview: ProjectOverview, location: ProjectLocation, client: ProjectContact, 
/**
 * The client's representative, when not the client.
 */
owner_rep: ProjectContact, team: Array<ProjectTeamMember>, budget: ProjectBudget, milestones: Array<ProjectMilestone>, codes: ProjectCodes, notes: string, };
