// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The budget's sums.
 */
export type ProjectBudgetTotals = { hard: number, soft: number, escalation: number, contingency: number, 
/**
 * Hard + soft + escalation + contingency.
 */
total: number, 
/**
 * Hard cost (with escalation) per gross sf; 0 without an area.
 */
hard_per_sf: number, 
/**
 * The owner's target construction cost per sf times the gross area (0: not set).
 */
target_hard: number, };
