// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";
import type { ElementId } from "./ElementId";
import type { Property } from "./Property";

export type PropertySheet = { id: ElementId, category: Category, title: string, typeId: ElementId | null, properties: Array<Property>, };
