// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PropKind } from "./PropKind";
import type { PropOption } from "./PropOption";

export type Property = { key: string, label: string, group: string, 
/**
 * Display text; for choices, the selected option id.
 */
value: string, kind: PropKind, options: Array<PropOption>, };
