// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Deliverable } from "./Deliverable";

/**
 * What Publish offers for the current design stage.
 */
export type PublishOptions = { 
/**
 * Rufplan phase tab: "sd", "dd" or "cd".
 */
phaseKind: string, stage: string, deliverables: Array<Deliverable>, 
/**
 * Sheets in the current stage's set.
 */
sheetCount: number, };
