// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppState } from "./AppState";

export type PublishResult = { state: AppState | null, 
/**
 * The Rufplan project page.
 */
url: string, published: Array<string>, 
/**
 * Files Rufplan refused, with the reason.
 */
skipped: Array<string>, };
