// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One finding Claude adds.
 */
export type QaClaudeFinding = { category: string, severity: string, title: string, detail: string, fix: string, reference: string, };
