// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QaClaudeFinding } from "./QaClaudeFinding";

export type QaClaudeReview = { overview: string, findings: Array<QaClaudeFinding>, };
