// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QaCategory } from "./QaCategory";

export type QaCount = { category: QaCategory, critical: number, major: number, minor: number, info: number, };
