// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";

/**
 * What a fix does to the model.
 */
export type QaFixAction = { "kind": "SetText", id: ElementId, key: string, value: string, } | { "kind": "Tag", view: ElementId, ids: Array<ElementId>, } | { "kind": "Stair", id: ElementId, max_riser: number | null, tread: number | null, width: number | null, railings: boolean | null, } | { "kind": "CeilingHeight", id: ElementId, height: number, } | { "kind": "Opening", id: ElementId, offset: number | null, sill: number | null, } | { "kind": "SwapType", ids: Array<ElementId>, type_id: ElementId, } | { "kind": "AddLayer", type_id: ElementId, index: number, name: string, } | { "kind": "RailingHeight", type_id: ElementId, height: number, } | { "kind": "RoofSlope", id: ElementId, slope: number, } | { "kind": "Delete", ids: Array<ElementId>, } | { "kind": "AddWindow", wall: ElementId, type_id: ElementId, offset: number, sill: number, } | { "kind": "Schedules" } | { "kind": "PlaceOnSheet", views: Array<ElementId>, name: string, } | { "kind": "GenerateSpecs" } | { "kind": "AddSpecs", numbers: Array<string>, } | { "kind": "IncludeSpecs", numbers: Array<string>, };
