// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QaFix } from "./QaFix";

export type QaFixPlan = { fixes: Array<QaFix>, 
/**
 * Findings that need the architect: id and why.
 */
manual: Array<[string, string]>, };
