// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { QaCategory } from "./QaCategory";
import type { QaSeverity } from "./QaSeverity";

/**
 * One thing the review found.
 */
export type QaFinding = { 
/**
 * Stable key (rule and element), for marking it resolved.
 */
id: string, rule: string, category: QaCategory, severity: QaSeverity, title: string, detail: string, 
/**
 * What to do about it.
 */
fix: string, 
/**
 * The code section, standard or practice it's measured against.
 */
reference: string, elements: Array<ElementId>, 
/**
 * Where to look: a plan of the element's level, or a sheet.
 */
view: ElementId | null, 
/**
 * "rules" or "claude".
 */
source: string, };
