// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QaFixAction } from "./QaFixAction";

export type QaFix = { 
/**
 * The finding it fixes.
 */
finding: string, title: string, 
/**
 * What will change, in words.
 */
change: string, 
/**
 * It changes the design (deletes, reshapes or adds), not just the documents.
 */
designChange: boolean, action: QaFixAction, };
