// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The milestone the set is reviewed for: early sets skip what isn't expected yet.
 */
export type QaMilestone = "SchematicDesign" | "DesignDevelopment" | "Cd50" | "Cd90" | "Cd100" | "Permit" | "Bid";
