// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QaCategory } from "./QaCategory";
import type { QaMilestone } from "./QaMilestone";

/**
 * What the review is asked to cover.
 */
export type QaOptions = { milestone: QaMilestone, categories: Array<QaCategory>, };
