// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QaCount } from "./QaCount";
import type { QaFinding } from "./QaFinding";
import type { QaMilestone } from "./QaMilestone";

export type QaReport = { milestone: QaMilestone, milestoneLabel: string, project: string, codeBasis: string, findings: Array<QaFinding>, counts: Array<QaCount>, 
/**
 * 0–100: 100 less 15 a critical, 5 a major, 1 a minor finding.
 */
score: number, summary: string, 
/**
 * Claude's overall review, when asked for.
 */
overview: string | null, checked: Array<string>, disclaimer: string, };
