// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QaFix } from "./QaFix";

/**
 * Claude's answer for one finding: its advice, and the fixes made from its operations.
 */
export type QaSuggestion = { finding: string, advice: string, fixes: Array<QaFix>, 
/**
 * Operations that didn't check out against the model, in words.
 */
dropped: Array<string>, };
