// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DimAnchor } from "./DimAnchor";
import type { Pt } from "./Pt";

/**
 * A reference under the cursor: a line (a wall face, centerline or core face, or a grid)
 * or a point.
 */
export type Reference = { 
/**
 * What it is, for the status bar ("Wall: exterior face", "Grid 3", "Point").
 */
label: string, 
/**
 * On the reference, nearest the cursor.
 */
at: Pt, 
/**
 * The reference's extent, to highlight (the same point twice for a point).
 */
from: Pt, to: Pt, 
/**
 * The line's direction (unit); None for a point.
 */
dir: Pt | null, anchor: DimAnchor | null, };
