// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { Pt } from "./Pt";

/**
 * A straight reference an element offers for Align: a wall face or centerline, or a grid.
 */
export type RefLine = { el: ElementId, a: Pt, b: Pt, };
