// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pt } from "./Pt";

/**
 * The mark's shape, in its view's coordinates.
 */
export type RefShape = { "Section": { start: Pt, end: Pt, } } | { "Callout": { min: Pt, max: Pt, } };
