// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";

/**
 * A view a reference can point at, as listed in the options bar.
 */
export type RefTarget = { id: ElementId, 
/**
 * "Drafting View: Typ. Eave", "Section: Section 2", "Detail View: Callout of Level 1".
 */
label: string, };
