// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Appearance } from "./Appearance";
import type { ElementId } from "./ElementId";

/**
 * A project material as the renderer needs it.
 */
export type RenderMaterial = { id: ElementId, name: string, color: [number, number, number], appearance: Appearance, };
