// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomKind } from "./RoomKind";

export type RoomSpec = { name: string, kind: RoomKind, 
/**
 * South-west corner and size, feet.
 */
x: number, y: number, width: number, depth: number, };
