// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Item } from "./Item";

export type RoomPreview = { 
/**
 * Outline of the enclosed area the room would fill; empty when not enclosed.
 */
items: Array<Item>, 
/**
 * Area of that region, or why a room can't go here.
 */
label: string, 
/**
 * True when a room can be placed here.
 */
valid: boolean, };
