// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a room is for: sets its doors, windows and whether it opens into its neighbours.
 */
export type RoomKind = "living" | "dining" | "kitchen" | "bedroom" | "bathroom" | "closet" | "laundry" | "garage" | "corridor" | "stair" | "entry" | "lobby" | "office" | "unit" | "guest_room" | "retail" | "amenity" | "mechanical" | "storage" | "other";
