// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The Rufplan.io project a model publishes to (ADR-016).
 */
export type RufplanLink = { 
/**
 * `open_projects.id`.
 */
id: string, name: string, 
/**
 * For the project page URL, rufplan.io/projects/<slug>.
 */
slug: string, };
