// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a schedule view lists.
 */
export type ScheduleKind = "Doors" | "Windows" | "Rooms" | "Sheets" | "Columns" | "Beams" | "MaterialTakeoff";
