// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextFont } from "./TextFont";

/**
 * How a schedule prints (ADR-110): its font, text sizes (paper mm) and row height, set per
 * schedule; the office's text types (ADR-109) when not set.
 */
export type ScheduleStyle = { font: TextFont, title: number, header: number, body: number, 
/**
 * Body row height, paper mm.
 */
row: number, };
