// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Criterion } from "./Criterion";
import type { LateralKind } from "./LateralKind";
import type { SchemeKind } from "./SchemeKind";
import type { SchemeSettings } from "./SchemeSettings";

/**
 * A candidate scheme, scored.
 */
export type SchemeProposal = { kind: SchemeKind, label: string, 
/**
 * 0–100.
 */
score: number, 
/**
 * Fails a hard limit (height or story count).
 */
ruledOut: boolean, criteria: Array<Criterion>, rationale: string, grid: string, memberDepths: Array<string>, redFlags: Array<string>, 
/**
 * Starting settings for Generate overlay.
 */
settings: SchemeSettings, laterals: Array<LateralKind>, };
