// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The candidate structural systems.
 */
export type SchemeKind = "LightWood" | "ColdFormedSteel" | "Podium" | "SteelFrame" | "ConcreteFlatPlate" | "MassTimber";
