// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LateralKind } from "./LateralKind";
import type { SchemeKind } from "./SchemeKind";
import type { Seismic } from "./Seismic";
import type { SpanDir } from "./SpanDir";

/**
 * What the user picked and adjusted before generating.
 */
export type SchemeSettings = { kind: SchemeKind, seismic: Seismic, 
/**
 * Target grid spacing each way, mm.
 */
gridX: number, gridY: number, lateral: LateralKind, spanDir: SpanDir, };
