// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A 3D view's section box (mm, model coordinates).
 */
export type SectionBox = { min: [number, number, number], max: [number, number, number], };
