// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a section is. The generated kinds are written from the project when the book is
 * shown or exported (Project Info, the team, the sheets), so they are never stale.
 */
export type SectionKind = "ThreePart" | "Document" | "TitlePage" | "ProjectDirectory" | "SealsPage" | "Contents" | "DrawingList";
