// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The site's seismic region, as the user sets it (no hazard data is looked up).
 */
export type Seismic = "Low" | "Moderate" | "High";
