// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingType } from "./BuildingType";
import type { Jurisdiction } from "./Jurisdiction";
import type { SheetSize } from "./SheetSize";

export type SetOptions = { buildingType: BuildingType, 
/**
 * Stage abbreviations to build sets for (PD, SD, DD, CD, BN, CA).
 */
phases: Array<string>, size: SheetSize, 
/**
 * Where it's permitted (ADR-104): shapes the general sheets. Project Info's location
 * when absent.
 */
jurisdiction?: Jurisdiction, };
