// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlannedDeliverable } from "./PlannedDeliverable";
import type { PlannedSheet } from "./PlannedSheet";

export type SetPlan = { deliverables: Array<PlannedDeliverable>, sheets: Array<PlannedSheet>, warnings: Array<string>, };
