// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppState } from "./AppState";
import type { ExportedSet } from "./ExportedSet";

export type SetsExported = { state: AppState | null, files: Array<ExportedSet>, };
