// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppState } from "./AppState";
import type { SetReport } from "./SetReport";

export type SetsCreated = { state: AppState | null, report: SetReport, };
