// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How Duplicate Sheet copies (Revit's three choices).
 */
export type SheetCopy = "Empty" | "WithDetailing" | "WithViews";
