// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A compass side, for the low edge of a shed roof.
 */
export type Side = "north" | "south" | "east" | "west";
