// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";

export type SiteSummary = { id: ElementId, address: string, lat: number, lon: number, hasTopo: boolean, 
/**
 * Lot corners as [lat, lon], for showing the lot on the map again.
 */
ring: Array<[number, number]>, };
