// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a sketch can't finish, with the curves to highlight (Revit's wording).
 */
export type SketchError = { message: string, bad: Array<number>, };
