// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pt } from "./Pt";
import type { WallRef } from "./WallRef";

export type SketchCurve = { "Line": { a: Pt, b: Pt, wall: WallRef | null, } } | { "Arc": { center: Pt, radius: number, start: number, sweep: number, } };
