// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pt } from "./Pt";

/**
 * A sketch curve as drawn: its points, and whether it's locked to a wall.
 */
export type SketchItem = { pts: Array<Pt>, locked: boolean, isLine: boolean, };
