// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { SketchItem } from "./SketchItem";
import type { SketchKind } from "./SketchKind";

export type SketchInfo = { kind: SketchKind, view: ElementId, target: ElementId | null, typeId: ElementId, curves: Array<SketchItem>, bad: Array<number>, error: string | null, canUndo: boolean, canRedo: boolean, };
