// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A sky in the library.
 */
export type SkyPreset = { 
/**
 * Poly Haven's asset id.
 */
id: string, name: string, 
/**
 * Clear, Partly Cloudy, Overcast, Sunrise & Sunset or Night.
 */
mood: string, 
/**
 * A word on the light, for the picker.
 */
note: string, };
