// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pt } from "./Pt";

/**
 * Where a floor's or ceiling's boundary comes from.
 */
export type SlabBound = "Sketch" | "Walls" | { "Room": { point: Pt, } };
