// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pt } from "./Pt";
import type { SnapKind } from "./SnapKind";

export type SnapResult = { pt: Pt, kind: SnapKind, 
/**
 * Length (and angle) from the previous point, formatted for display.
 */
label: string | null, };
