// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which content goes in.
 */
export type SpecContent = "Full" | "Short" | "Narrative";
