// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The type family: a Times-metric serif, a Calibri-metric sans, or the Rufplan face.
 */
export type SpecFont = "Serif" | "Sans" | "Brand";
