// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpecContent } from "./SpecContent";
import type { SpecFont } from "./SpecFont";
import type { SpecHeading } from "./SpecHeading";
import type { SpecNumbering } from "./SpecNumbering";

export type SpecStyle = { id: string, name: string, description: string, numbering: SpecNumbering, font: SpecFont, 
/**
 * Body size, pt.
 */
size: number, heading: SpecHeading, content: SpecContent, 
/**
 * Article titles in bold.
 */
boldArticles: boolean, 
/**
 * Each section on new pages, numbered "09 29 00 - 1" (else one run of pages).
 */
pagePerSection: boolean, 
/**
 * Left and right margins, inches.
 */
margin: number, 
/**
 * Space between paragraphs, pt.
 */
gap: number, };
