// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpecDiffLine } from "./SpecDiffLine";

export type SpecChange = { number: string, title: string, 
/**
 * "added", "removed", "changed", "included", "excluded", "renumbered".
 */
kind: string, added: number, removed: number, 
/**
 * The changed lines with a line of context, up to 80.
 */
lines: Array<SpecDiffLine>, };
