// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpecSection } from "./SpecSection";

/**
 * The book: its sections in number order, the style it's issued in, and the issue.
 */
export type SpecBook = { 
/**
 * A studio-specs style id ("csi-classic"…).
 */
style: string, 
/**
 * "Issued for Permit", "Bid Set"…
 */
issue: string, 
/**
 * ISO date, or empty.
 */
date: string, sections: Array<SpecSection>, };
