// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpecParagraph } from "./SpecParagraph";

export type SpecArticle = { title: string, paragraphs: Array<SpecParagraph>, };
