// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One paragraph: its level (0: A., 1: 1., 2: a., 3: 1)) and text.
 */
export type SpecParagraph = { level: number, text: string, };
