// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How articles and paragraphs are numbered.
 */
export type SpecNumbering = "Csi" | "CsiZero" | "Decimal" | "Bullets";
