// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpecArticle } from "./SpecArticle";

/**
 * A part: "GENERAL", "PRODUCTS", "EXECUTION"; a document section has one untitled part.
 */
export type SpecPart = { title: string, articles: Array<SpecArticle>, };
