// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a section's title is set.
 */
export type SpecHeading = "Centered" | "Ruled" | "Banner";
