// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpecReference = { 
/**
 * The sections the reference is in.
 */
from: Array<string>, 
/**
 * The section it points to.
 */
to: string, 
/**
 * Its title, if the library has it (it can then be added).
 */
title: string | null, 
/**
 * In the book but excluded.
 */
excluded: boolean, };
