// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpecParty } from "./SpecParty";

/**
 * What the generated front matter is written from.
 */
export type SpecFront = { projectName: string, projectNumber: string, address: string, owner: SpecParty | null, 
/**
 * The architect, then the engaged consultants.
 */
team: Array<SpecParty>, 
/**
 * Sheet number and name, in number order.
 */
sheets: Array<[string, string]>, };
