// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpecOpPart } from "./SpecOpPart";

/**
 * One operation. `op`: "replace_section", "add_section", "remove_section", "include",
 * "exclude", "renumber".
 */
export type SpecOp = { op: string, number: string, title?: string, new_number?: string, 
/**
 * The section's whole text (replace, or add a section not in the library).
 */
parts?: Array<SpecOpPart>, };
