// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SectionKind } from "./SectionKind";
import type { SectionOrigin } from "./SectionOrigin";
import type { SpecPart } from "./SpecPart";

export type SpecSection = { 
/**
 * MasterFormat number, "09 29 00" (optionally ".11").
 */
number: string, 
/**
 * Upper case, "GYPSUM BOARD".
 */
title: string, kind: SectionKind, parts: Array<SpecPart>, 
/**
 * Excluded sections stay in the book (their text kept) but aren't issued.
 */
included: boolean, origin: SectionOrigin, 
/**
 * Changed since it came from the library.
 */
edited: boolean, };
