// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpecOpArticle = { title: string, 
/**
 * Paragraphs in the shorthand: one leading ">" per level.
 */
paragraphs: Array<string>, };
