// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpecOpArticle } from "./SpecOpArticle";

export type SpecOpPart = { title: string, articles: Array<SpecOpArticle>, };
