// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One library section as the Add Sections dialog lists it.
 */
export type SpecLibraryRow = { number: string, title: string, paragraphs: number, 
/**
 * The model and Project Info call for it, and why.
 */
picked: boolean, reason: string | null, inBook: boolean, };
