// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpecOp } from "./SpecOp";

export type SpecEdit = { operations: Array<SpecOp>, summary: string, 
/**
 * Why nothing could be done, or a note for the architect.
 */
message: string, };
