// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpecBook } from "./SpecBook";
import type { SpecDivision } from "./SpecDivision";
import type { SpecFront } from "./SpecFront";
import type { SpecLibraryRow } from "./SpecLibraryRow";
import type { SpecReference } from "./SpecReference";
import type { SpecStyle } from "./SpecStyle";

/**
 * Everything the Specifications tab shows.
 */
export type SpecState = { book: SpecBook | null, styles: Array<SpecStyle>, library: Array<SpecLibraryRow>, divisions: Array<SpecDivision>, 
/**
 * Cross-references to sections missing from the book (or excluded).
 */
references: Array<SpecReference>, 
/**
 * Sections in the book the model no longer calls for.
 */
unindicated: Array<string>, 
/**
 * Sections the model calls for that aren't in the book.
 */
indicated: Array<string>, 
/**
 * What the generated front matter is written from.
 */
front: SpecFront, today: string, };
