// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A person or firm on the project, for the directory and seals page.
 */
export type SpecParty = { role: string, company: string, name: string, address: string, phone: string, email: string, };
