// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What Update from Model did.
 */
export type SpecUpdate = { 
/**
 * Sections the model now calls for, added.
 */
added: Array<string>, 
/**
 * Library sections in the book the model no longer calls for (left in, to review).
 */
unindicated: Array<string>, };
