// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpecChange } from "./SpecChange";
import type { SpecEdit } from "./SpecEdit";

/**
 * Claude's proposal and what it changes (or why it can't be done).
 */
export type SpecEditPlan = { edit: SpecEdit, changes: Array<SpecChange>, error: string | null, };
