// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";

export type StageItem = { id: ElementId, name: string, abbreviation: string, };
