// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Plan shape of a stair.
 */
export type StairShape = "Straight" | { "LShaped": { left: boolean, } } | { "UShaped": { left: boolean, } };
