// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One standard: its office value, preset choices (if any) and whether it's defined.
 */
export type StandardItem = { name: string, value: string, options?: Array<string>, done: boolean, };
