// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StandardItem } from "./StandardItem";

export type StandardCategory = { id: string, label: string, 
/**
 * The ribbon button's label.
 */
short: string, 
/**
 * SHEETS, ANNOTATION, GRAPHICS, DATA, VIEWS or OUTPUT.
 */
group: string, applies: Array<string>, items: Array<StandardItem>, };
