// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayList } from "./DisplayList";

/**
 * One way a standard can be set, as the Standards pop-up shows it (ADR-048).
 */
export type StandardChoice = { label: string, detail: string, 
/**
 * What it looks like, for graphic standards (paper mm).
 */
preview: DisplayList | null, };
