// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StandardCategory } from "./StandardCategory";

/**
 * The project's standards: the library they started from and every category.
 */
export type Standards = { library: string, categories: Array<StandardCategory>, };
