// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomSpec } from "./RoomSpec";
import type { StoryRoof } from "./StoryRoof";

export type StorySpec = { 
/**
 * Floor to floor, feet.
 */
height: number, rooms: Array<RoomSpec>, 
/**
 * The library material on this story's outside walls (ADR-099); the building's
 * exterior walls' when absent.
 */
cladding?: string, 
/**
 * The roof over what nothing above covers; the building's roof when absent.
 */
roof?: StoryRoof, };
