// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomSpec } from "./RoomSpec";

export type StorySpec = { 
/**
 * Floor to floor, feet.
 */
height: number, rooms: Array<RoomSpec>, };
