// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoofKind } from "./RoofKind";
import type { Side } from "./Side";

/**
 * The roof over the part of a story nothing above covers (ADR-099).
 */
export type StoryRoof = { kind: RoofKind, 
/**
 * Rise per 12; the building's pitch when absent.
 */
pitch?: number, 
/**
 * A shed roof's low side; away from the volume above, else north, when absent.
 */
lowSide?: Side, };
