// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { FlagKind } from "./FlagKind";
import type { Pt } from "./Pt";

/**
 * A red flag at a point, with its explanation.
 */
export type StructFlag = { kind: FlagKind, level: ElementId | null, at: Pt, message: string, };
