// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SchemeProposal } from "./SchemeProposal";
import type { Seismic } from "./Seismic";

/**
 * Suggest Structure's answer: every scheme ranked, best first.
 */
export type StructuralProposal = { disclaimer: string, seismic: Seismic, schemes: Array<SchemeProposal>, assumptions: Array<string>, questions: Array<string>, 
/**
 * A short summary of what was found.
 */
summary: Array<string>, };
