// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { MemberKind } from "./MemberKind";
import type { Pt } from "./Pt";

/**
 * One member: at a point (columns, `start` = `end`) or along a line, on `level`, from
 * elevation `base` up to `top` (mm).
 */
export type StructMember = { kind: MemberKind, level: ElementId, start: Pt, end: Pt, base: number, top: number, 
/**
 * Preliminary size, e.g. "W12x26 (prelim.)" or "11-7/8\" I-joist @ 16\" o.c.".
 */
size: string, 
/**
 * Depth and width, mm (for drawing).
 */
depth: number, width: number, 
/**
 * Span or height, mm.
 */
span: number, 
/**
 * The rule that placed and sized it, in words.
 */
rule: string, };
