// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StructFlag } from "./StructFlag";
import type { StructMember } from "./StructMember";

/**
 * The generated preliminary layout.
 */
export type StructLayout = { 
/**
 * Grid line positions, mm: x values of lines running north–south, y of east–west.
 */
gridX: Array<number>, gridY: Array<number>, members: Array<StructMember>, flags: Array<StructFlag>, 
/**
 * Whole-building notes (lateral balance, assumptions).
 */
notes: Array<string>, };
