// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { SchemeSettings } from "./SchemeSettings";
import type { StructLayout } from "./StructLayout";

/**
 * The structural layer for the panel and exports.
 */
export type StructuralLayer = { id: ElementId, settings: SchemeSettings, layout: StructLayout, disclaimer: string, };
