// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Revit's Sun Settings > Solar Study: Still (a date and time at the site) or Lighting
 * (a sun at an azimuth and altitude).
 */
export type SunMode = "Still" | "Lighting";
