// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the sun is.
 */
export type SunPosition = { 
/**
 * Unit vector toward the sun in model space (x east of project north's right, z up).
 */
dir: [number, number, number], 
/**
 * Degrees above the horizon.
 */
altitude: number, 
/**
 * Degrees clockwise from true north.
 */
azimuth: number, };
