// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SunMode } from "./SunMode";

export type SunSettings = { mode: SunMode, month: number, day: number, 
/**
 * Hours of local standard time (15.5 = 3:30 PM).
 */
hour: number, 
/**
 * Lighting mode: degrees clockwise from true north, and above the horizon.
 */
azimuth: number, altitude: number, };
