// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a material's surface reads in elevations (lines at true size, mm).
 */
export type SurfacePattern = "None" | { "Lap": { spacing: number, } } | { "Running": { course: number, unit: number, } } | { "Grid": { width: number, height: number, } };
