// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A sweep's profile, square to its path: a rectangle centered across the path from its
 * elevation up, or a round bar sitting on its elevation.
 */
export type SweepProfile = { "Rectangle": { width: number, height: number, } } | { "Circle": { diameter: number, } };
