// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MepCriterion } from "./MepCriterion";
import type { MepSettings } from "./MepSettings";

/**
 * A candidate system, scored.
 */
export type SystemProposal = { key: string, label: string, description: string, 
/**
 * 0–100.
 */
score: number, ruledOut: boolean, criteria: Array<MepCriterion>, rationale: string, 
/**
 * Its key numbers: loads, equipment, sizes.
 */
highlights: Array<string>, redFlags: Array<string>, settings: MepSettings, };
