// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";

export type Table = { title: string, columns: Array<string>, rows: Array<Array<string>>, 
/**
 * Element each row describes (for selecting from the schedule).
 */
ids: Array<ElementId>, };
