// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { Item } from "./Item";
import type { Pt } from "./Pt";

/**
 * A temporary dimension; clicking its value lets the user type a new one, sent as
 * `set_temp_dimension(id, key, text)`.
 */
export type TempDim = { id: ElementId, key: string, value: string, labelAt: Pt, items: Array<Item>, };
