// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContourLabel } from "./ContourLabel";
import type { ElementId } from "./ElementId";
import type { TerrainContour } from "./TerrainContour";

export type Terrain = { site: ElementId, 
/**
 * The contour interval, mm (the Site's Contour Interval property).
 */
interval: number, 
/**
 * The block's sides and bottom, triangles (9 floats each).
 */
skirt: Array<number>, contours: Array<TerrainContour>, labels: Array<ContourLabel>, };
