// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerrainContour = { 
/**
 * Absolute elevation, mm.
 */
elevation: number, 
/**
 * Every fifth interval, drawn heavier.
 */
major: boolean, 
/**
 * Segments on the ground, 6 floats each (project mm, z-up).
 */
segments: Array<number>, };
