// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The fonts a set prints in (ADR-110): the drafting font everything uses, and two the
 * schedules and notes can switch to, each bundled so the PDF embeds it.
 */
export type TextFont = "Drafting" | "Sans" | "Serif";
