// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Maps of a photo texture set.
 */
export type TextureMap = "color" | "normal" | "roughness";
