// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { Pt } from "./Pt";

/**
 * A selected text note's box, drawn round it as Revit does: bottom left, bottom right, top
 * right, top left, turned with the note (ADR-108).
 */
export type TextFrame = { id: ElementId, corners: [Pt, Pt, Pt, Pt], };
