// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { Pt } from "./Pt";
import type { TextAlign } from "./TextAlign";

/**
 * A text note as the in-place editor needs it (ADR-070).
 */
export type TextNoteInfo = { text: string, at: Pt, 
/**
 * Paper mm.
 */
size: number, align: TextAlign, 
/**
 * Paper mm.
 */
width: number | null, view: ElementId, 
/**
 * The box, model mm, before turning.
 */
min: Pt, max: Pt, 
/**
 * Rotation about `at`, radians counter-clockwise (ADR-108).
 */
angle: number, };
