// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DoorSpec } from "./DoorSpec";
import type { ElementId } from "./ElementId";
import type { WindowSpec } from "./WindowSpec";

/**
 * What a thumbnail shows: a project type, or a door or window size to load.
 */
export type ThumbSource = { "Type": ElementId } | { "Door": DoorSpec } | { "Window": WindowSpec };
