// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { License } from "./License";
import type { SignedBy } from "./SignedBy";

/**
 * Everything the title block prints that isn't worked out (date, scale, issues).
 */
export type TitleBlockFields = { sheetNumber: string, sheetName: string, projectName: string, projectNumber: string, 
/**
 * The owner (the client's company).
 */
client: string, street: string, city: string, state: string, zip: string, firm: string, firmAddress: string, firmPhone: string, firmEmail: string, firmWebsite: string, license: License, signed: SignedBy, };
