// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A grid of ground elevations in the site's local frame (mm; absolute elevations in mm
 * above the NAVD88 datum, as 3DEP reports them).
 */
export type Topo = { x0: number, y0: number, spacing: number, nx: number, ny: number, z: Array<number>, 
/**
 * Finest source resolution in the samples, m (1 = lidar).
 */
resolution: number, };
