// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A building use read from room names.
 */
export type UseKind = "Residential" | "Office" | "Retail" | "Parking" | "Assembly" | "Education";
