// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingUse } from "./BuildingUse";

export type UseOption = { id: BuildingUse, label: string, };
