// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CameraPose } from "./CameraPose";
import type { Category } from "./Category";
import type { DetailLevel } from "./DetailLevel";
import type { ElementId } from "./ElementId";
import type { SectionBox } from "./SectionBox";
import type { ViewType } from "./ViewType";

export type ViewInfo = { id: ElementId, name: string, viewType: ViewType, scale: number, scaleLabel: string, level: ElementId | null, 
/**
 * Sheet this view is placed on, if any (schedules may be on several; this is the first).
 */
onSheet: ElementId | null, 
/**
 * For sheets: the design stages whose sets include it.
 */
stages: Array<ElementId>, 
/**
 * 3D views: the section box, when on.
 */
sectionBox: SectionBox | null, 
/**
 * Callouts: the view they detail.
 */
calloutOf: ElementId | null, 
/**
 * Hide in View: categories hidden, and how many elements are hidden one by one.
 */
hiddenCategories: Array<Category>, hiddenCount: number, 
/**
 * A site plan (satellite overlay, ADR-026).
 */
site: boolean, 
/**
 * Camera views: the camera in model space (ADR-027).
 */
camera: CameraPose | null, 
/**
 * Drawn views (plans, elevations, sections): their Detail Level (ADR-067).
 */
detailLevel: DetailLevel | null, 
/**
 * Visibility/Graphics > Worksets: worksets hidden in this view (ADR-079).
 */
hiddenWorksets: Array<ElementId>, };
