// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { Pt } from "./Pt";

/**
 * A perspective camera on a 3D view. Heights are above `level`, so the camera moves with
 * it.
 */
export type ViewCamera = { level: ElementId, eye: Pt, eyeHeight: number, target: Pt, targetHeight: number, 
/**
 * Vertical field of view, degrees.
 */
fov: number, };
