// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { Pt } from "./Pt";

/**
 * A viewport's sheet, view and center (paper mm), for activating it (ADR-039).
 */
export type ViewportInfo = { sheet: ElementId, view: ElementId, center: Pt, };
