// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { ViewType } from "./ViewType";

export type ViewInfo = { id: ElementId, name: string, viewType: ViewType, scale: number, scaleLabel: string, level: ElementId | null, };
