// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { LayerFunction } from "./LayerFunction";

/**
 * One layer of a compound wall type. Layers are listed from the exterior face inward;
 * the exterior face is on the wall's left, looking from its start to its end (walls drawn
 * clockwise have their exterior outside, as in Revit).
 */
export type WallLayer = { 
/**
 * Layer description, e.g. "Gypsum Board" (the material's name when one is picked).
 */
name: string, 
/**
 * mm.
 */
thickness: number, function: LayerFunction, 
/**
 * The layer's material (ADR-020); None falls back to rules on the name.
 */
material: ElementId | null, };
