// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which line of a wall a locked sketch line follows.
 */
export type WallFace = "Exterior" | "Interior" | "CoreExterior" | "CoreInterior" | "Centerline";
