// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Axis } from "./Axis";
import type { ElementId } from "./ElementId";
import type { Pt } from "./Pt";

/**
 * A wall, for stacking and lateral candidates.
 */
export type WallFeature = { id: ElementId, level: ElementId, start: Pt, end: Pt, length: number, thickness: number, exterior: boolean, axis: Axis, 
/**
 * Length taken by doors and windows, mm.
 */
openingLength: number, 
/**
 * Opening-free stretches as distances along it from its start, mm.
 */
solid: Array<[number, number]>, 
/**
 * Whether walls on the level below carry it.
 */
stacks: boolean, 
/**
 * Around a stair, elevator or shaft.
 */
atCore: boolean, };
