// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerFunction } from "./LayerFunction";

/**
 * One layer of a compound wall type. Layers are listed from the exterior face inward;
 * the exterior face is on the wall's left, looking from its start to its end (walls drawn
 * clockwise have their exterior outside, as in Revit).
 */
export type WallLayer = { 
/**
 * Material name, e.g. "Gypsum Board".
 */
name: string, 
/**
 * mm.
 */
thickness: number, function: LayerFunction, };
