// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WallFrame } from "./WallFrame";

/**
 * A wall face as the sketch's work plane (ADR-058), and how the sketch's coordinates map
 * onto it: in an elevation or section they are the view's (x across, y the elevation),
 * with the wall's u = `a` + `s`·x and z = y − `z_off`; in 3D they are the wall's own
 * (u, z) (a = 0, s = 1, z_off = 0).
 */
export type WallPlane = { frame: WallFrame, a: number, s: number, zOff: number, };
