// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { WallFace } from "./WallFace";

/**
 * A sketch line locked to a wall face, `offset` mm further out from the wall.
 */
export type WallRef = { wall: ElementId, face: WallFace, offset: number, };
