// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { Pt } from "./Pt";

/**
 * A wall face as a sketch's work plane (mm): the location line's start and direction,
 * the face's side and distance from the centerline, and the wall's base and length.
 */
export type WallFrame = { wall: ElementId, start: Pt, dir: Pt, 
/**
 * The face's outward normal in plan (the wall's left, `dir.perp()`, or its right).
 */
normal: Pt, 
/**
 * The face's distance from the centerline (half the thickness).
 */
half: number, base_z: number, length: number, height: number, };
