// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A line of a window's elevation, in (u, z) from its bottom-left seen from outside.
 */
export type WindowLine = { pts: Array<[number, number]>, closed: boolean, dashed: boolean, 
/**
 * Pen weight, 1 finest.
 */
w: number, 
/**
 * The outline of a pane of glass (thumbnails fill it).
 */
glass: boolean, };
