// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WindowPreview } from "./WindowPreview";
import type { WindowSpec } from "./WindowSpec";

/**
 * A standard size: its spec (mm, no grille, white) and the type name it loads as.
 */
export type WindowPresetInfo = { spec: WindowSpec, name: string, preview: WindowPreview, };
