// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrameFinish } from "./FrameFinish";
import type { Grille } from "./Grille";
import type { WindowFamily } from "./WindowFamily";

/**
 * The building's windows (ADR-031): a family for bedrooms, kitchens and offices (living
 * spaces and units take its twin), with a grille and frame finish.
 */
export type WindowChoice = { family: WindowFamily | null, grille: Grille, finish: FrameFinish, };
