// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FinishOption } from "./FinishOption";
import type { GrilleOption } from "./GrilleOption";
import type { WindowFamilyInfo } from "./WindowFamilyInfo";
import type { WindowPresetInfo } from "./WindowPresetInfo";

export type WindowLibrary = { families: Array<WindowFamilyInfo>, presets: Array<WindowPresetInfo>, grilles: Array<GrilleOption>, finishes: Array<FinishOption>, };
