// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WindowLine } from "./WindowLine";

/**
 * A Window Library thumbnail: the outline and elevation lines of a style at a size.
 */
export type WindowPreview = { width: number, height: number, lines: Array<WindowLine>, };
