// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrameFinish } from "./FrameFinish";
import type { Grille } from "./Grille";
import type { WindowFamily } from "./WindowFamily";

/**
 * A window type to load: a family at a size, with options. Lengths mm.
 */
export type WindowSpec = { family: WindowFamily, units: number, width: number, height: number, sill: number, grille: Grille, finish: FrameFinish, };
