// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Built-in window families: the common US window types (ADR-031, see `windows`).
 */
export type WindowFamily = "Fixed" | "Casement" | "DoubleHung" | "SingleHung" | "Awning" | "Hopper" | "Slider" | "Slider3" | "PictureCasement" | "PictureAwning" | "Bay" | "Storefront";
