// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";
import type { WorksetRole } from "./WorksetRole";

/**
 * A workset for the Worksets dialog.
 */
export type WorksetInfo = { id: ElementId, name: string, role: WorksetRole, visibleInAllViews: boolean, 
/**
 * Elements on it (explicitly or by default).
 */
count: number, };
