// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a workset is for: which elements fall back to it.
 */
export type WorksetRole = "Default" | "LevelsGrids" | "Structural" | "Other";
